(function(g){var window=this;var REa=function(a,b){return g.$b(a,b)},c6=function(a){g.eo(a,"zx",g.Ac());
return a},d6=function(a,b,c){g.Ha(c)||(c=[String(c)]);
g.ho(a.o,b,c)},SEa=function(a,b){var c=[];
g.Pl(b,function(d){try{var e=g.FE.prototype.A.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ba(e)?g.EE(e)&&c.push(d):c.push(d)},a);
return c},TEa=function(a,b){var c=SEa(a,b);
(0,g.C)(c,function(d){g.FE.prototype.remove.call(this,d)},a)},UEa=function(a){if(a.Ld){if(a.Ld.locationOverrideToken)return{locationOverrideToken:a.Ld.locationOverrideToken};
if(null!=a.Ld.latitudeE7&&null!=a.Ld.longitudeE7)return{latitudeE7:a.Ld.latitudeE7,longitudeE7:a.Ld.longitudeE7}}return null},VEa=function(a,b,c,d){var e=new g.Vn(null,void 0);
a&&g.Wn(e,a);b&&g.Xn(e,b);c&&g.Yn(e,c);d&&g.Zn(e,d);return e},e6=function(a,b){g.yF[a]=!0;
var c=g.wF();c&&c.publish.apply(c,arguments);g.yF[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.C=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Pn;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",WEa(this,a.capabilities||""),XEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},WEa=function(a,b){a.capabilities.clear();
(0,g.se)(b.split(","),g.Na(REa,YEa)).forEach(function(c){a.capabilities.add(c)})},XEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},ZEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},$Ea=function(a){return new g6(a)},aFa=function(a){return g.Ha(a)?(0,g.J)(a,$Ea):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Ha(a)?"["+(0,g.J)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},bFa=function(a){return(0,g.J)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.Wa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.Wa(a,function(c){return h6(c,b)})},cFa=function(){var a=(0,g.LI)();
a&&TEa(a,a.o.be(!0))},n6=function(){var a=g.OI("yt-remote-connected-devices")||[];
g.ub(a);return a},dFa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(d,e){return 0==e?d:d.substring(c.length)})},eFa=function(a){g.NI("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.OI("yt-remote-device-id");a||(a=k6(),g.NI("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.ab(a,b);g.QI()&&g.wb(a,b);a=dFa(a);if(g.bb(a))try{g.mI("remote_sid")}catch(c){}else try{g.lI("remote_sid",a.join(","),-1)}catch(c){}},fFa=function(){return g.OI("yt-remote-session-browser-channel")},gFa=function(){return g.OI("yt-remote-local-screens")||[]},hFa=function(){g.NI("yt-remote-lounge-token-expiration",!0,86400)},iFa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)(gFa(),function(d){return d.loungeToken}),c=(0,g.J)(a,function(d){return d.loungeToken});
(0,g.Gj)(c,function(d){return!g.ab(b,d)})&&hFa();
g.NI("yt-remote-local-screens",a,31536E3)},jFa=function(a,b){g.NI("yt-remote-session-browser-channel",a);
g.NI("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.ab(c,d)||c.push(d);eFa(c);q6()},r6=function(a){a||(g.PI("yt-remote-session-screen-id"),g.PI("yt-remote-session-video-id"));
q6();a=n6();g.fb(a,p6());eFa(a)},kFa=function(){if(!s6){var a=g.QE();
a&&(s6=new g.zE(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},lFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?mFa(a.shift(),function(){u6(a)}):v6()},nFa=function(a){return"chrome-extension://"+a+w6},mFa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=lFa();
a&&a(!1,"No cast extension found")},pFa=function(){if(oFa){var a=2,b=lFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;mFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},qFa=function(){pFa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.K.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Fd=b;this.D=(0,g.A)(this.cL,this);this.o=!1;this.A=0;this.C=this.Ea=null;this.B=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.C=b;this.G=c;this.F=d||1;this.B=45E3;this.Z=new g.lo(this);this.A=new g.ch;this.A.setInterval(250)},sFa=function(a,b,c){a.gk=1;
a.Ah=c6(b.clone());a.mj=c;a.D=!0;rFa(a,null)},A6=function(a,b,c,d,e){a.gk=1;
a.Ah=c6(b.clone());a.mj=null;a.D=c;e&&(a.KF=!1);rFa(a,d)},rFa=function(a,b){a.bl=(0,g.H)();
B6(a);a.ai=a.Ah.clone();d6(a.ai,"t",a.F);a.jo=0;a.Tc=a.o.Wt(a.o.Yn()?b:null);0<a.Eu&&(a.qr=new g.wm((0,g.A)(a.VG,a,a.Tc),a.Eu));a.Z.X(a.Tc,"readystatechange",a.gV);var c=a.Ji?g.jc(a.Ji):{};a.mj?(a.ls="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Tc.send(a.ai,a.ls,a.mj,c)):(a.ls="GET",a.KF&&!g.ge&&(c.Connection="close"),a.Tc.send(a.ai,a.ls,null,c));a.o.Af(1)},vFa=function(a,b,c){for(var d=!0;!a.ri&&a.jo<c.length;){var e=tFa(a,c);
if(e==C6){4==b&&(a.Bh=4,D6(15),d=!1);break}else if(e==uFa){a.Bh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Bh=1,D6(17),d=!1);a.Gf=a.Gf&&d;d||(F6(a),G6(a))},tFa=function(a,b){var c=a.jo,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return uFa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.jo=d+c;return e},xFa=function(a,b){a.bl=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.ai=a.Ah.clone();g.eo(a.ai,"DOMAIN",c);g.eo(a.ai,"t",a.F);try{a.If=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Bh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in wFa)k=H6[l]=wFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Ed(g.Wc("b/12014412"),d+"</body></html>");a.If.open();a.If.write(g.xd(c));a.If.close();a.If.parentWindow.m=(0,g.A)(a.oU,a);a.If.parentWindow.d=(0,g.A)(a.YE,a,!0);a.If.parentWindow.rpcClose=(0,g.A)(a.YE,a,!1);c=a.If.createElement("DIV");a.If.parentWindow.document.body.appendChild(c);d=g.kd(a.ai.toString());d=g.uc(g.hd(d));d=g.Ed(g.Wc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Fd(c,d);a.o.Af(1)},B6=function(a){a.Ay=(0,g.H)()+a.B;
yFa(a,a.B)},yFa=function(a,b){if(null!=a.El)throw Error("WatchDog timer not null");
a.El=I6((0,g.A)(a.DU,a),b)},J6=function(a){a.El&&(g.x.clearTimeout(a.El),a.El=null)},G6=function(a){a.o.NB()||a.ri||a.o.Rq(a)},F6=function(a){J6(a);
g.Pf(a.qr);a.qr=null;a.A.stop();g.ro(a.Z);if(a.Tc){var b=a.Tc;a.Tc=null;b.abort();b.dispose()}a.If&&(a.If=null)},E6=function(a,b){try{a.o.RE(a,b),a.o.Af(4)}catch(c){}},AFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;zFa(a,b,function(k){k?c(!0):g.x.setTimeout(function(){AFa(a,b,c,d,f)},f)})}},zFa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},BFa=function(a){this.o=a;
this.A=new y6},CFa=function(a){var b=L6(a.o,a.Tl,"/mail/images/cleardot.gif");
c6(b);AFa(b.toString(),5E3,(0,g.A)(a.dK,a),3,2E3);a.Af(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.me=new z6(a,void 0,void 0,void 0),a.me.Ji=a.Cu,b=a.o,b=L6(b,b.Yn()?a.Mm:null,a.Du),D6(5),!g.ee||g.Oc(10))d6(b,"TYPE","xmlhttp"),A6(a.me,b,!1,a.Mm,!1);else{d6(b,"TYPE","html");var c=a.me;a=!!a.Mm;c.gk=3;c.Ah=c6(b.clone());xFa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.B=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},DFa=function(a,b){this.o=a;
this.map=b;this.context=null},EFa=function(a){g.Rf.call(this,"statevent",a)},FFa=function(a,b){g.Rf.call(this,"timingevent",a);
this.size=b},GFa=function(a){g.Rf.call(this,"serverreachability",a)},JFa=function(a){HFa(a);
if(3==a.o){var b=a.En++,c=a.xp.clone();g.eo(c,"SID",a.C);g.eo(c,"RID",b);g.eo(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.C,b,void 0);b.gk=2;b.Ah=c6(c.clone());(new Image).src=b.Ah;b.bl=(0,g.H)();B6(b)}IFa(a)},KFa=function(a){a.AK(1,0);
a.xp=L6(a,null,a.Bu);Q6(a)},HFa=function(a){a.qh&&(a.qh.abort(),a.qh=null);
a.zc&&(a.zc.cancel(),a.zc=null);a.Dg&&(g.x.clearTimeout(a.Dg),a.Dg=null);R6(a);a.ge&&(a.ge.cancel(),a.ge=null);a.uh&&(g.x.clearTimeout(a.uh),a.uh=null)},LFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new DFa(a.ZP++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.ge||a.uh||(a.uh=I6((0,g.A)(a.XE,a),0),a.Xj=0)},NFa=function(a,b){if(1==a.o){if(!b){a.En=Math.floor(1E5*Math.random());
var c=a.En++,d=new z6(a,"",c,void 0);d.Ji=null;var e=S6(a),f=a.xp.clone();g.eo(f,"RID",c);g.eo(f,"CVER","1");P6(a,f);sFa(d,f,e);a.ge=d;a.o=2}}else 3==a.o&&(b?MFa(a,b):0==a.A.length||a.ge||MFa(a))},MFa=function(a,b){if(b)if(6<a.wi){a.A=a.B.concat(a.A);
a.B.length=0;var c=a.En-1;var d=S6(a)}else c=b.G,d=b.mj;else c=a.En++,d=S6(a);var e=a.xp.clone();g.eo(e,"SID",a.C);g.eo(e,"RID",c);g.eo(e,"AID",a.Ak);P6(a,e);c=new z6(a,a.C,c,a.Xj+1);c.Ji=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ge=c;sFa(c,e,d)},P6=function(a,b){if(a.Ed){var c=a.Ed.tB();
c&&g.Ob(c,function(d,e){g.eo(b,e,d)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.wi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.wi?e:f-d;try{g.Ob(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.A.splice(0,b));
return c.join("&")},OFa=function(a){a.zc||a.Dg||(a.G=1,a.Dg=I6((0,g.A)(a.WE,a),0),a.Nj=0)},T6=function(a){if(a.zc||a.Dg||3<=a.Nj)return!1;
a.G++;a.Dg=I6((0,g.A)(a.WE,a),PFa(a,a.Nj));a.Nj++;return!0},M6=function(a,b,c){a.gs=c;
a.Uf=b.Rg;a.F||KFa(a)},R6=function(a){null!=a.yi&&(g.x.clearTimeout(a.yi),a.yi=null)},PFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Ed&&(c=null);var d=(0,g.A)(a.XV,a);c||(c=new g.Vn("//www.google.com/images/cleardot.gif"),c6(c));zFa(c.toString(),1E4,d)}else D6(2);QFa(a,b)},QFa=function(a,b){a.o=0;
a.Ed&&a.Ed.rA(b);IFa(a);HFa(a)},IFa=function(a){a.o=0;
a.Uf=-1;if(a.Ed)if(0==a.B.length&&0==a.A.length)a.Ed.It();else{g.kb(a.B);var b=g.kb(a.A);a.B.length=0;a.A.length=0;a.Ed.It(b)}},L6=function(a,b,c){var d=g.fo(c);
if(""!=d.A)b&&g.Xn(d,b+"."+d.A),g.Yn(d,d.D);else{var e=window.location;d=VEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.pm&&g.Ob(a.pm,function(f,k){g.eo(d,k,f)});
g.eo(d,"VER",a.wi);P6(a,d);return d},I6=function(a,b){if(!g.Ja(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new EFa(V6,a))},RFa=function(){},SFa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.K.call(this);
this.o=new g.V(this.eU,0,this);g.L(this,this.o);this.Fd=5E3;this.A=0;if(g.Ja(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ja(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.C=a},X6=function(a,b,c){this.K=a;
this.F=b;this.C=new g.yE;this.A=new W6(this.zW,this);this.o=this.jb=null;this.Bb=!1;this.D=null;this.J="";this.H=this.B=0;this.G=[];this.L=c||!1},TFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.gs,sessionId:a.o.C,arrayId:a.o.Ak}},UFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&NFa(a.o),JFa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},VFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.rh(a)||"";b&&(this.port=":"+b);this.domain=g.qh(a)||"";a=g.Lb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Kb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.Ba(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Ah(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Na(a.B,d,!0),onError:g.Na(a.C,e),Id:g.Na(a.D,e)};c&&(a.Rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.hG(b,a)},ZFa=function(){var a=WFa;
XFa();b7.push(a);YFa(b7)},c7=function(a,b){XFa();
var c=b7,d=$Fa(a,String(b));g.bb(c)?aGa(d):(YFa(c),(0,g.C)(c,function(e){e(d)}))},XFa=function(){b7||(b7=g.y("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",b7,void 0))},aGa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},YFa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(f){f(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},$Fa=function(a,b){var c=((0,g.H)()-bGa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.zH.call(this);
this.G=a;this.o=[]},cGa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},dGa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.se)(a.o,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=cGa(a,b[d])||c;return c},eGa=function(a,b){var c=a.o.length;
a.o=(0,g.se)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.zH.call(this);
this.F=a;this.D=b;this.C=c;this.B=d;this.A=0;this.o=null;this.Ea=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.C=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},fGa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(d){return d.id}),c=$6(a.C,"/pairing/get_lounge_token_batch");
a7(a.C,c,{screen_ids:b.join(",")},(0,g.A)(a.qL,a),(0,g.A)(a.pL,a))}},i7=function(a){var b=aFa(gFa());
b=(0,g.se)(b,function(c){return!c.uuid});
return dGa(a,b)},k7=function(a,b){iFa((0,g.J)(a.o,ZEa));
b&&hFa()},m7=function(a,b){g.zH.call(this);
this.F=b;var c=g.OI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.o=d;this.D=a;this.C=this.B=NaN;this.A=null;l7("Initialized with "+g.ih(this.o))},gGa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Ub(b)!=g.Ub(a.o))var c=!1;
else{c=g.Xb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.ih(a.o)),a.o=b,a.U("screenChange"));hGa(a)},o7=function(a){isNaN(a.C)||g.vF(a.C);
a.C=g.tF((0,g.A)(a.ox,a),0<a.B&&a.B<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},iGa=function(a){var b={};
(0,g.C)(a.F(),function(c){c.token?b[c.token]=c.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},hGa=function(a){a=g.Xb(g.Pb(a.o,function(b){return b}));
g.ub(a);a.length?g.NI("yt-remote-online-screen-ids",a.join(","),60):g.PI("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.C=null;this.B=[];this.D={};jGa(this)},lGa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ye();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);gGa(a.A,l,function(m){e(m?l:null)})}else c?kGa(a,c,(0,g.A)(function(m){var n=q7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));gGa(this.A,n,function(p){e(p?n:null)})},a),f):e(null)},mGa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},kGa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.hG($6(a.F,"/pairing/get_lounge_token_batch"),e)},nGa=function(a){a.o=a.C.ye();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},jGa=function(a){r7(a);
a.C=new j7(a.F);a.C.subscribe("screenChange",(0,g.A)(a.DL,a));nGa(a);a.B=aFa(g.OI("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.B));a.A=new m7(a.F,(0,g.A)(a.ye,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.U("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),g.NI("yt-remote-automatic-screen-cache",(0,g.J)(a.B,ZEa)));r7(a);a.D[b.uuid]=b.id;g.NI("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.OI("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.zH.call(this);
this.M=c;this.J=a;this.A=b;this.C=null},t7=function(a,b){c7(a.M,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.B=0;this.F=(0,g.A)(this.GW,this);this.D=(0,g.A)(this.PU,this);this.B=g.tF((0,g.A)(function(){oGa(this,null)},this),12E4)},pGa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.ih(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.ih(b))},oGa=function(a,b){g.vF(a.B);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.C||a.C.id!=b){var c=(0,g.A)(a.Sq,a),d=(0,g.A)(a.De,a);a.EB(b,c,d,5)}}else a.De(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.B=this.H=null;this.K="";this.V=c;this.D=null;this.G=g.z;this.F=NaN;this.L=(0,g.A)(this.JW,this);this.o=g.z},qGa=function(a){a.o=a.J.ZG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(b){this.o=g.z;
this.Sq(b)},a),(0,g.A)(function(b){this.o=g.z;
this.De(b)},a))},rGa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.V;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}kFa()&&(b.env_useStageMdx=1);return g.yh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.tF((0,g.A)(this.Ck,this,null),150)},x7=function(a,b,c,d){g.zH.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.C=[];this.B=(0,g.A)(this.kT,this)},sGa=function(a,b){return b?g.Wa(a.C,function(c){return h6(b,c.label)},a):null},y7=function(a){c7("Controller",a)},WFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.C.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.Pf(a.o),(a.o=b)?(c?a.U("yt-remote-cast2-receiver-resumed",b.A):a.U("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.UE,a,b)),b.C?a.U("yt-remote-cast2-session-change",b.C):c&&a.o.Ck(null)):a.U("yt-remote-cast2-session-change",null))},tGa=function(a){var b=a.A.YG(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=sGa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},zGa=function(a,b,c,d,e,f,k){uGa()?vGa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?wGa(a,c):(window.__onGCastApiAvailable=function(l,m){l?wGa(a,c):(D7("Failed to load cast API: "+m),E7(!1),C7(!1),g.PI("yt-remote-cast-available"),g.PI("yt-remote-cast-receiver"),xGa(),c(!1))},d?g.GF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?qFa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(pFa(),u6(yGa.map(nFa))))):B7("Cannot initialize because not running Chrome")},xGa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);AGa(!1);g.BF(G7);G7.length=0},H7=function(){return!!g.OI("yt-remote-cast-installed")},BGa=function(){var a=g.OI("yt-remote-cast-receiver");
return a?a.friendlyName:null},CGa=function(){B7("clearCurrentReceiver");
g.PI("yt-remote-cast-receiver")},DGa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.AF("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},uGa=function(){var a=0<=g.Lb.search(/ (CrMo|Chrome|CriOS)\//);
return g.nM||a},EGa=function(a,b){F7().init(a,b)},vGa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.NI("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){B7("onReceiverSelected: "+f.friendlyName);
g.NI("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){B7("onReceiverResumed: "+f.friendlyName);
g.NI("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){B7("onSessionChange: "+i6(f));
f||g.PI("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},wGa=function(a,b){E7(!0);
C7(!1);EGa(a,function(c){c?(AGa(!0),g.DF("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.PI("yt-remote-cast-available"),g.PI("yt-remote-cast-receiver"),xGa());b(c)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.NI("yt-remote-cast-installed",a)},I7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},AGa=function(a){B7("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Yf=!1;this.J=this.H=this.A=this.B=0;this.C=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Yf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.B=0;a.A=0;a.H=0;a.J=0;a.C=NaN;a.D=!1},N7=function(a){return a.sb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.kc(a.o);b.hasPrevious=a.Yf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.C;return b},T7=function(a,b){g.zH.call(this);
this.o=0;this.B=a;this.F=[];this.D=new g.PD;this.C=this.A=null;this.J=(0,g.A)(this.KQ,this);this.G=(0,g.A)(this.Hn,this);this.H=(0,g.A)(this.JQ,this);this.K=(0,g.A)(this.WQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Iy,this),FGa(this))):c=3;0!=c&&(b?this.Iy(c):g.tF((0,g.A)(function(){this.Iy(c)},this),0));
var d=DGa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.B.getPlayerContextData())},FGa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Na(this.gT,b),this))},a)},GGa=function(a){(0,g.C)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},V7=function(a,b){50>a.D.Gc()&&g.RD(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.B.sendMessage(b,c)},W7=function(a,b){GGa(a);
a.B.setPlayerContextData(R7(b));FGa(a)},S7=function(a,b){a.C&&(a.C.removeUpdateListener(a.J),a.C.removeMediaListener(a.G),a.Hn(null));
a.C=b;a.C&&(c7("CP","Setting cast session: "+a.C.sessionId),a.C.addUpdateListener(a.J),a.C.addMediaListener(a.G),a.C.media.length&&a.Hn(a.C.media[0]))},HGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(d){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.zH.call(this);
this.D=NaN;this.V=!1;this.K=this.J=this.L=this.M=NaN;this.O=[];this.B=this.G=this.C=this.kb=this.o=null;this.sa=a;this.O.push(g.iH(window,"beforeunload",(0,g.A)(this.gL,this)));this.A=[];this.kb=new L7;this.aa=b.id;this.o=IGa(this,c);this.o.subscribe("handlerOpened",this.OQ,this);this.o.subscribe("handlerClosed",this.LQ,this);this.o.subscribe("handlerError",this.MQ,this);this.o.subscribe("handlerMessage",this.NQ,this);VFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.kb.videoId;
g.QI()&&g.NI("yt-remote-session-video-id",d)},this)},a8=function(a){c7("conn",a)},IGa=function(a,b){return new X6($6(a.sa,"/bc"),b)},b8=function(a,b){a.U("proxyStateChange",b)},JGa=function(a){a.D=g.tF((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.vF(a.D);
a.D=NaN},d8=function(a){g.vF(a.M);
a.M=NaN},KGa=function(a){e8(a);
a.L=g.tF((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.vF(a.L);
a.L=NaN},MGa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Y()&&a.kb.reset(),b8(a,1),f8(a,"getNowPlaying"),LGa(a)):a.F(1)},NGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.kb.videoId&&(g.ec(b.params)?a.kb.o=null:a.kb.o=b.params,a.U("remotePlayerChange"))},OGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.kb.listId=b.params.listId||a.kb.listId;Q7(a.kb,c,d);a.U("remoteQueueChange")},QGa=function(a,b){b.params=b.params||{};
OGa(a,b);PGa(a,b);a.U("autoplayDismissed")},PGa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.kb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.kb.playerState&&(c=-1E3);a.kb.playerState=c;c=Number(b.params.loadedTime);a.kb.J=isNaN(c)?0:c;c=Number(b.params.duration);a.kb.H=isNaN(c)?0:c;c=a.kb;var d=Number(b.params.liveIngestionTime);c.C=d;c.D=isNaN(d)?!1:!0;c=a.kb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.kb.playerState?KGa(a):e8(a);a.U("remotePlayerChange")},RGa=function(a,b){if(-1E3!=
a.kb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.kb.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.kb,isNaN(c)?0:c);a.U("remotePlayerChange")}},SGa=function(a,b){var c="true"==b.params.muted;
a.kb.volume=parseInt(b.params.volume,10);a.kb.muted=c;a.U("remotePlayerChange")},TGa=function(a,b){a.G=b.params.videoId;
a.U("nowAutoplaying",parseInt(b.params.timeout,10))},UGa=function(a,b){var c="true"==b.params.hasNext;
a.kb.Yf="true"==b.params.hasPrevious;a.kb.hasNext=c;a.U("previousNextChange")},LGa=function(a){g.vF(a.K);
a.K=g.tF((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.ih(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.jd=a;this.A=[];this.A.push(this.jd.$_s("screenChange",(0,g.A)(this.EW,this)));this.A.push(this.jd.$_s("onlineScreenChange",(0,g.A)(this.FS,this)))},ZGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.kF("MDX_CONFIG")||b;cFa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),kFa()&&(h8.o="/api/loungedev"));i8||(i8=g.y("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",i8,void 0));VGa();var c=j8();if(!c){var d=new p7(h8);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);zGa(a,d,function(m){m?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.ih(b)),m8.push(g.AF("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.AF("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.AF("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.AF("yt-remote-cast2-session-change",WGa)),m8.push(g.AF("yt-remote-connection-change",function(m){m?K7(k8(),"YouTube TV"):o8()||(K7(null,null),CGa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.ZF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.ih(a)),XGa(a),c.start(),k8()||YGa())},aHa=function(){var a=$Ga();
H7()&&g.OI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},$Ga=function(){var a=j8().jd.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return bFa(a)},s8=function(){var a=bHa();
!a&&H7()&&BGa()&&(a={key:"cast-selector-receiver",name:BGa()});return a},bHa=function(){var a=$Ga(),b=q8();
b||(b=o8());return g.Wa(a,function(c){return b&&h6(b,c.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().ye();return m6(b,a)},WGa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.y("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.y("yt.mdx.remote.currentScreenId_")},cHa=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},dHa=function(){return g.y("yt.mdx.remote.connectData_")},n8=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.y("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||cHa("");g.Ea("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(c){c(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.QI();
if(!a)return null;var b=j8().ye();return m6(b,a)},u8=function(a,b){q8()&&q8();
cHa(a.id);var c=new $7(h8,a,p8());c.connect(b,dHa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},YGa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),CGa(),l8("Skipping connecting because no session screen found."))},VGa=function(){var a=p8();
if(g.ec(a)){a=p6();var b=g.OI("yt-remote-session-name")||"",c=g.OI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},XGa=function(a){a?(g.NI("yt-remote-session-app",a.app),g.NI("yt-remote-session-name",a.name)):(g.PI("yt-remote-session-app"),g.PI("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.K.call(this);
this.D=a;this.A=b;this.C=new g.wH(this);g.L(this,this.C);this.C.R(b,"onCaptionsTrackListChanged",this.YR);this.C.R(b,"captionschanged",this.IQ);this.C.R(b,"captionssettingschanged",this.nG);this.C.R(b,"videoplayerreset",this.Tq);this.C.R(b,"mdxautoplaycancel",this.cK);this.O=this.C.R(b,"onVolumeChange",this.BE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.QE,this);c.subscribe("remotePlayerChange",this.Kn,this);c.subscribe("remoteQueueChange",this.Tq,this);c.subscribe("autoplayUpNext",this.nE,
this);c.subscribe("previousNextChange",this.NE,this);c.subscribe("nowAutoplaying",this.FE,this);c.subscribe("autoplayDismissed",this.mE,this);this.suggestion=null;this.J=new g.IQ(64);this.B=new g.V(this.kG,500,this);g.L(this,this.B);this.F=new g.V(this.lG,1E3,this);g.L(this,this.F);this.L=new x6(this.hW,0,this);g.L(this,this.L);this.G={};this.M=new g.V(this.LG,1E3,this);g.L(this,this.M);this.K=new g.wm(this.FO,1E3,this);g.L(this,this.K);this.V=g.z;this.nG();this.Tq();this.Kn()},z8=function(a,b){a.D.He(b,
a.A.getVideoData().lengthSeconds)},eHa=function(a){z8(a,0);
a.B.stop();A8(a,new g.IQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.mc(c,b));a.o.YF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.xe();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.uk,UEa(c));A8(a,new g.IQ(1))},fHa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{F4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.OQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.TU(a.A,d);a.J=b;gHa(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
N:"ytp-remote",P:[{I:"div",N:"ytp-remote-display-status",P:[{I:"div",N:"ytp-remote-display-status-icon",P:[g.rta()]},{I:"div",N:"ytp-remote-display-status-text",ca:"{{statustext}}"}]}]});this.B=new g.JV(this,250);g.L(this,this.B);this.D=a;this.R(a,"presentingplayerstatechange",this.F);hHa(this,g.PU(a))},hHa=function(a,b){if(3==a.D.getPresentingPlayerType()){var c={RECEIVER_NAME:a.D.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.wV("Error on $RECEIVER_NAME",c):b.sb()||g.X(b,4)?g.wV("Playing on $RECEIVER_NAME",c):g.wV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.$W.call(this,"Play on",0,a,b);
this.B=a;this.K={};this.R(a,"onMdxReceiversChange",this.M);this.R(a,"presentingplayerstatechange",this.M);this.M()},G8=function(a){g.mV.call(this,a);
this.A={key:k6(),name:"This computer"};this.B=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.C=this.A;this.vn=new g.IQ(64);this.J=0;this.H=-1;if(!g.nO(g.Y(this.player))){a=this.player;var b=g.xQ(a);b&&(b=b.xn())&&(b=new F8(a,b),g.L(this,b));b=new E8(a);g.L(this,b);g.dV(a,b.element,4)}},gHa=function(a,b,c){a.vn=c;
a.player.U("presentingplayerstatechange",new g.SQ(c,b))},H8=function(a,b){if(b.key!=a.C.key)if(b.key==a.A.key)t8();
else{a.C=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.za(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.uk,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=UEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.ih(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().ye(),(d=m6(d,b.key))&&u8(d,1))}},wFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},iHa={},YEa={cY:"atp",J2:"ska",W1:"que",e1:"mus",F2:"sus",o_:"dsp",p2:"seq"};
f6.prototype.rh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.C=this.C;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",oFa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),yGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.K);g.h=x6.prototype;g.h.bL=function(a){this.B=arguments;this.o=!1;this.Ea?this.C=(0,g.H)()+this.Fd:this.Ea=g.dh(this.D,this.Fd)};
g.h.stop=function(){this.Ea&&(g.eh(this.Ea),this.Ea=null);this.C=null;this.o=!1;this.B=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.h.W=function(){this.stop();x6.fa.W.call(this)};
g.h.cL=function(){this.C?(this.Ea=g.dh(this.D,this.C-(0,g.H)()),this.C=null):(this.Ea=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};y6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Ji=null;g.h.Gf=!1;g.h.El=null;g.h.Ay=null;g.h.bl=null;g.h.gk=null;g.h.Ah=null;g.h.ai=null;g.h.mj=null;g.h.Tc=null;g.h.jo=0;g.h.If=null;g.h.ls=null;g.h.Bh=null;g.h.Nm=-1;g.h.KF=!0;g.h.ri=!1;g.h.Eu=0;g.h.qr=null;var uFa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.gV=function(a){a=a.target;var b=this.qr;b&&3==g.My(a)?b.Jm():this.VG(a)};
g.h.VG=function(a){try{if(a==this.Tc)a:{var b=g.My(this.Tc),c=this.Tc.A,d=this.Tc.getStatus();if(g.ee&&!g.Oc(10)||g.ge&&!g.Nc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Tf&&!g.Qy(this.Tc))break a;this.ri||4!=b||7==c||(8==c||0>=d?this.o.Af(3):this.o.Af(2));J6(this);var e=this.Tc.getStatus();this.Nm=e;var f=g.Qy(this.Tc);(this.Gf=200==e)?(4==b&&F6(this),this.D?(vFa(this,b,f),g.Tf&&this.Gf&&3==b&&(this.Z.X(this.A,"tick",this.bV),this.A.start())):E6(this,f),this.Gf&&!this.ri&&(4==b?this.o.Rq(this):
(this.Gf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Bh=3,D6(13)):(this.Bh=0,D6(14)),F6(this),G6(this))}}catch(k){this.Tc&&g.Qy(this.Tc)}finally{}};
g.h.bV=function(){var a=g.My(this.Tc),b=g.Qy(this.Tc);this.jo<b.length&&(J6(this),vFa(this,a,b),this.Gf&&4!=a&&B6(this))};
g.h.oU=function(a){I6((0,g.A)(this.nU,this,a),0)};
g.h.nU=function(a){this.ri||(J6(this),E6(this,a),B6(this))};
g.h.YE=function(a){I6((0,g.A)(this.mU,this,a),0)};
g.h.mU=function(a){this.ri||(F6(this),this.Gf=a,this.o.Rq(this),this.o.Af(4))};
g.h.cancel=function(){this.ri=!0;F6(this)};
g.h.DU=function(){this.El=null;var a=(0,g.H)();0<=a-this.Ay?(2!=this.gk&&this.o.Af(3),F6(this),this.Bh=2,D6(18),G6(this)):yFa(this,this.Ay-a)};
g.h.getLastError=function(){return this.Bh};g.h=BFa.prototype;g.h.Cu=null;g.h.me=null;g.h.rr=!1;g.h.OB=null;g.h.vp=null;g.h.Iv=null;g.h.Du=null;g.h.We=null;g.h.Rg=-1;g.h.Mm=null;g.h.Tl=null;g.h.connect=function(a){this.Du=a;a=L6(this.o,null,this.Du);D6(3);this.OB=(0,g.H)();var b=this.o.H;null!=b?(this.Mm=b[0],(this.Tl=b[1])?(this.We=1,CFa(this)):(this.We=2,N6(this))):(d6(a,"MODE","init"),this.me=new z6(this,void 0,void 0,void 0),this.me.Ji=this.Cu,A6(this.me,a,!1,null,!0),this.We=0)};
g.h.dK=function(a){if(a)this.We=2,N6(this);else{D6(4);var b=this.o;b.Uf=b.qh.Rg;U6(b,9)}a&&this.Af(2)};
g.h.Wt=function(a){return this.o.Wt(a)};
g.h.abort=function(){this.me&&(this.me.cancel(),this.me=null);this.Rg=-1};
g.h.NB=function(){return!1};
g.h.RE=function(a,b){this.Rg=a.Nm;if(0==this.We)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Uf=this.Rg;U6(c,2);return}this.Mm=c[0];this.Tl=c[1]}else c=this.o,c.Uf=this.Rg,U6(c,2);else if(2==this.We)if(this.rr)D6(7),this.Iv=(0,g.H)();else if("11111"==b){if(D6(6),this.rr=!0,this.vp=(0,g.H)(),c=this.vp-this.OB,!g.ee||g.Oc(10)||500>c)this.Rg=200,this.me.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.vp=this.Iv=(0,g.H)(),this.rr=!1};
g.h.Rq=function(){this.Rg=this.me.Nm;if(this.me.Gf)0==this.We?this.Tl?(this.We=1,CFa(this)):(this.We=2,N6(this)):2==this.We&&((!g.ee||g.Oc(10)?!this.rr:200>this.Iv-this.vp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.We?D6(9):2==this.We&&D6(10);var a=this.o;this.me.getLastError();a.Uf=this.Rg;U6(a,2)}};
g.h.Yn=function(){return this.o.Yn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Af=function(a){this.o.Af(a)};g.h=O6.prototype;g.h.pm=null;g.h.ge=null;g.h.zc=null;g.h.Bu=null;g.h.xp=null;g.h.hA=null;g.h.Kp=null;g.h.En=0;g.h.ZP=0;g.h.Ed=null;g.h.uh=null;g.h.Dg=null;g.h.yi=null;g.h.qh=null;g.h.gs=null;g.h.Ak=-1;g.h.EC=-1;g.h.Uf=-1;g.h.Xj=0;g.h.Nj=0;g.h.wi=8;var V6=new g.sg;g.B(EFa,g.Rf);g.B(FFa,g.Rf);g.B(GFa,g.Rf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Bu=b;this.pm=c||{};d&&g.Ba(e)&&(this.pm.OSID=d,this.pm.OAID=e);this.F?(I6((0,g.A)(this.zA,this,a),100),KFa(this)):this.zA(a)};
g.h.zA=function(a){this.qh=new BFa(this);this.qh.Cu=null;this.qh.A=this.D;this.qh.connect(a)};
g.h.NB=function(){return 0==this.o};
g.h.XE=function(a){this.uh=null;NFa(this,a)};
g.h.WE=function(){this.Dg=null;this.zc=new z6(this,this.C,"rpc",this.G);this.zc.Ji=null;this.zc.Eu=0;var a=this.hA.clone();g.eo(a,"RID","rpc");g.eo(a,"SID",this.C);g.eo(a,"CI",this.gs?"0":"1");g.eo(a,"AID",this.Ak);P6(this,a);if(!g.ee||g.Oc(10))g.eo(a,"TYPE","xmlhttp"),A6(this.zc,a,!0,this.Kp,!1);else{g.eo(a,"TYPE","html");var b=this.zc,c=!!this.Kp;b.gk=3;b.Ah=c6(a.clone());xFa(b,c)}};
g.h.RE=function(a,b){if(0!=this.o&&(this.zc==a||this.ge==a))if(this.Uf=a.Nm,this.ge==a&&3==this.o)if(7<this.wi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Ha(c)&&3==c.length)if(0==c[0])a:{if(!this.Dg){if(this.zc)if(this.zc.bl+3E3<this.ge.bl)R6(this),this.zc.cancel(),this.zc=null;else break a;T6(this);D6(19)}}else this.EC=c[1],0<this.EC-this.Ak&&37500>c[2]&&this.gs&&0==this.Nj&&!this.yi&&(this.yi=I6((0,g.A)(this.DQ,this),6E3));else U6(this,11)}else b!=iHa.fZ.o&&U6(this,11);else if(this.zc==a&&
R6(this),!g.E(b)){c=this.D.parse(b);g.Ha(c);for(var d=0;d<c.length;d++){var e=c[d];this.Ak=e[0];e=e[1];2==this.o?"c"==e[0]?(this.C=e[1],this.Kp=e[2],e=e[3],null!=e?this.wi=e:this.wi=6,this.o=3,this.Ed&&this.Ed.tA(),this.hA=L6(this,this.Yn()?this.Kp:null,this.Bu),OFa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Ed&&this.Ed.sA(e),this.Nj=0)}}};
g.h.DQ=function(){null!=this.yi&&(this.yi=null,this.zc.cancel(),this.zc=null,T6(this),D6(20))};
g.h.Rq=function(a){if(this.zc==a){R6(this);this.zc=null;var b=2}else if(this.ge==a)this.ge=null,b=1;else return;this.Uf=a.Nm;if(0!=this.o)if(a.Gf)1==b?(b=(0,g.H)()-a.bl,V6.dispatchEvent(new FFa(V6,a.mj?a.mj.length:0,b,this.Xj)),Q6(this),this.B.length=0):OFa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.ge||this.uh||1==this.o||2<=this.Xj?d=!1:(this.uh=I6((0,g.A)(this.XE,this,a),PFa(this,this.Xj)),this.Xj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.AK=function(a){if(!g.ab(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.XV=function(a){a?D6(2):(D6(1),QFa(this,8))};
g.h.Wt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Gy;a.H=!1;return a};
g.h.isActive=function(){return!!this.Ed&&this.Ed.isActive(this)};
g.h.Af=function(a){V6.dispatchEvent(new GFa(V6,a))};
g.h.Yn=function(){return!(!g.ee||g.Oc(10))};
g.h=RFa.prototype;g.h.tA=function(){};
g.h.sA=function(){};
g.h.rA=function(){};
g.h.It=function(){};
g.h.tB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.K);g.h=W6.prototype;g.h.eU=function(){this.Fd=Math.min(3E5,2*this.Fd);this.C();this.A&&this.start()};
g.h.start=function(){var a=this.Fd+15E3*Math.random();g.Fv(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Fd=5E3};g.B(X6,RFa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.C.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.C.unsubscribe(a,b,c)};
g.h.Fk=function(a){return this.C.Ki(a)};
g.h.U=function(a,b){return this.C.U.apply(this.C,arguments)};
g.h.dispose=function(){this.Bb||(this.Bb=!0,g.Pf(this.C),UFa(this),g.Pf(this.A),this.A=null)};
g.h.la=function(){return this.Bb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.B=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Ed=null);d.Ed=this;this.o=d;e?this.o.connect(a,b,this.F,e.C,e.Ak):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.mc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&LFa(this.o,c)};
g.h.tA=function(){this.A.reset();this.D=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)LFa(this.o,a[b])}this.U("handlerOpened")};
g.h.rA=function(a){var b=2==a&&401==this.o.Uf;4==a||b||this.A.start();this.U("handlerError",a)};
g.h.It=function(a){if(!this.A.isActive())this.U("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.tB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.D&&g.mc(a,this.D);return a};
g.h.sA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),JFa(this.o)):this.U("handlerMessage",new SFa(a[0],a[1]))};
g.h.zW=function(){this.A.isActive();var a=this.o,b=0;a.zc&&b++;a.ge&&b++;0!=b||this.connect(this.D,this.B)};Z6.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.C=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var bGa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.zH);g7.prototype.ye=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.zH);var jHa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ea)&&this.XG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ea)||(g.vF(this.Ea),this.Ea=NaN)};
g.h.W=function(){this.stop();h7.fa.W.call(this)};
g.h.XG=function(){this.Ea=NaN;this.o=g.hG($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.BW,this),onError:(0,g.A)(this.AW,this),Id:(0,g.A)(this.DW,this)})};
g.h.BW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.B;this.U("pairingComplete",new g6(c))};
g.h.AW=function(a){this.o=null;a.status&&404==a.status?this.A>=jHa.length?this.U("pairingFailed",Error("DIAL polling timed out")):(a=jHa[this.A],this.Ea=g.tF((0,g.A)(this.XG,this),a),this.A++):this.U("pairingFailed",Error("Server error "+a.status))};
g.h.DW=function(){this.o=null;this.U("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.U("screenChange");!g.OI("yt-remote-lounge-token-expiration")&&fGa(this);g.vF(this.A);this.A=g.tF((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);cGa(this,a);k7(this,!1);this.U("screenChange");b(a);a.token||fGa(this)};
g.h.remove=function(a,b){var c=i7(this);eGa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.U("screenChange")};
g.h.Yr=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.U("screenChange")};
g.h.W=function(){g.vF(this.A);j7.fa.W.call(this)};
g.h.qL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.pL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.zH);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.OI("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.H)()-144E5<a?0:a)?o7(this):(this.B=(0,g.H)()+3E5,g.NI("yt-remote-fast-check-period",this.B),this.ox())};
g.h.isEmpty=function(){return g.ec(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Pb(this.o,function(c,d){return c&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.vF(this.C);this.C=NaN;this.A&&(this.A.abort(),this.A=null);m7.fa.W.call(this)};
g.h.ox=function(){g.vF(this.C);this.C=NaN;this.A&&this.A.abort();var a=iGa(this);if(g.Ub(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Xb(a).join(",")},(0,g.A)(this.GT,this,a),(0,g.A)(this.FT,this))}else n7(this,{}),o7(this)};
g.h.GT=function(a,b){this.A=null;var c=g.Xb(iGa(this));if(g.vb(c,g.Xb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.sc("Changing Screen set during request."),this.ox()};
g.h.FT=function(a){this.sc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.sc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.C.start();this.A.start();this.o.length&&(this.U("screenChange"),this.A.isEmpty()||this.U("onlineScreenChange"))};
g.h.add=function(a,b,c){this.C.add(a,b,c)};
g.h.remove=function(a,b,c){this.C.remove(a,b,c);this.A.update()};
g.h.Yr=function(a,b,c,d){this.C.contains(a)?this.C.Yr(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.ye=function(a){return a?this.o:g.jb(this.o,(0,g.se)(this.B,function(b){return!this.contains(b)},this))};
g.h.YG=function(){return(0,g.se)(this.ye(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.ZG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(k){g.Pf(f);d(q7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Pf(f);e(k)});
f.start();return(0,g.A)(f.stop,f)};
g.h.FW=function(a,b,c,d){g.hG($6(this.F,"/pairing/get_screen"),{method:"POST",Rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(e,f){var k=new g6(f.screen||{});if(!k.name||mGa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);mGa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(q7(this,k))},this),
onError:(0,g.A)(function(e){d(Error("pairing request failed: "+e.status))},this),
Id:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Pf(this.C);g.Pf(this.A);p7.fa.W.call(this)};
g.h.DL=function(){nGa(this);this.U("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.zH);g.h=s7.prototype;g.h.Sq=function(a){this.C=a;this.U("sessionScreen",this.C)};
g.h.De=function(a){this.la()||(a&&t7(this,""+a),this.C=null,this.U("sessionScreen",null))};
g.h.info=function(a){c7(this.M,a)};
g.h.bH=function(){return null};
g.h.Ex=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Ex("");s7.fa.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.Dx=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);pGa(this)};
g.h.Ck=function(a){this.info("launchWithParams no-op for Cast: "+g.ih(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.De()},this),(0,g.A)(function(){this.De(Error("Failed to stop receiver app."))},this)):this.De(Error("Stopping cast device witout session."))};
g.h.Ex=g.z;g.h.W=function(){this.info("disposeInternal");g.vF(this.B);this.B=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.fa.W.call(this)};
g.h.PU=function(a,b){if(!this.la())if(b){var c=g.By(b);if(g.Ka(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.ih(c));switch(d){case "mdxSessionStatus":oGa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.EB=function(a,b,c,d){lGa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.tF((0,g.A)(this.EB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.bH=function(){return this.o};
g.h.GW=function(a){this.la()||a||(t7(this,"Cast session died."),this.De())};g.B(v7,s7);g.h=v7.prototype;g.h.Dx=function(a){this.B=a;this.B.addUpdateListener(this.L)};
g.h.Ck=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.vF(this.F);this.B?this.B.stop((0,g.A)(this.De,this,null),(0,g.A)(this.De,this,"Failed to stop DIAL device.")):this.De()};
g.h.W=function(){this.o();this.o=g.z;g.vF(this.F);this.B&&this.B.removeUpdateListener(this.L);this.B=null;v7.fa.W.call(this)};
g.h.JW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.z,this.De())};
g.h.fv=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,rGa(this));a(b);qGa(this)}else this.G=(0,g.A)(function(){g.vF(this.F);this.G=g.z;this.F=NaN;var c=new chrome.cast.DialLaunchResponse(!0,rGa(this));a(c);qGa(this)},this),this.F=g.tF((0,g.A)(function(){this.G()},this),100)};
g.h.QM=function(a,b,c){lGa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(d){d&&d.token?(this.Sq(d),b(new chrome.cast.DialLaunchResponse(!1))):this.fv(b,c)},this),(0,g.A)(function(d){t7(this,"Failed to get DIAL screen: "+d);
this.fv(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.De()};
w7.prototype.Dx=g.z;w7.prototype.Ck=function(){g.vF(this.o);this.o=NaN;var a=m6(this.J.ye(),this.A.label);a?this.Sq(a):this.De(Error("No such screen"))};
w7.prototype.W=function(){g.vF(this.o);this.o=NaN;w7.fa.W.call(this)};g.B(x7,g.zH);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.TE,this),(0,g.A)(this.oT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.lR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.B),ZFa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.aH,this)),this.C=tGa(this),chrome.cast.setCustomReceivers(this.C,g.z,(0,g.A)(function(f){this.sc("Failed to set initial custom receivers: "+g.ih(f))},this)),this.U("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(f){this.sc("Failed to initialize API: "+g.ih(f));
b(!1)},this))};
g.h.FV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.C;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.ye(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=sGa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.C.push(d),chrome.cast.setCustomReceivers(this.C,
g.z,(0,g.A)(function(e){this.sc("Failed to set initial custom receivers: "+g.ih(e))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Ex(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.GV=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.Ck(a):this.sc("Setting connection data without a session")};
g.h.IW=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.TE,this),(0,g.A)(this.KT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.aH,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);g.fb(g.y("yt.mdx.remote.debug.handlers_")||[],WFa);g.Pf(this.o);x7.fa.W.call(this)};
g.h.sc=function(a){c7("Controller",a)};
g.h.UE=function(a,b){this.o==a&&(b||A7(this,null),this.U("yt-remote-cast2-session-change",b))};
g.h.kT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.C&&this.U("yt-remote-cast2-session-change",this.o.C);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.lR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.C)return y7("Reselecting dial screen."),
this.U("yt-remote-cast2-session-change",this.o.C),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.QM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.fv,b))};
g.h.TE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.ye(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Pf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.UE,this,this.o)),this.o.Ck(null));this.o.Dx(a)}}};
g.h.HW=function(){return this.o?this.o.bH():null};
g.h.KT=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.ih(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.oT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.U("yt-remote-cast2-availability-change",z7(this))}};
g.h.aH=function(){this.la()||(this.C=tGa(this),y7("Updating custom receivers: "+g.ih(this.C)),chrome.cast.setCustomReceivers(this.C,g.z,(0,g.A)(function(){this.sc("Failed to set custom receivers.")},this)),this.U("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.GV;x7.prototype.setConnectedScreenStatus=x7.prototype.FV;x7.prototype.stopSession=x7.prototype.IW;x7.prototype.getCastSession=x7.prototype.HW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Yf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.C=a.liveIngestionTime,this.D=!isNaN(this.C))};
g.h.sb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.zH);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.U("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.sb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.U("remotePlayerChange")}else V7(this,g.Na(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.U("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.C){if(c.volume!=a){var d=Math.round(a)/100;this.C.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.C.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.Na(this.setVolume,a,b))};
g.h.YF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.ih(b.style),g.mc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.Na(this.YF,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){Y7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ob.id});var c=U7(this);c.audioTrackId=b.Ob.id;W7(this,c)}else V7(this,g.Na(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.Ba(b)&&(O7(l,b),m.currentTime=b);g.Ba(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.ih(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.Zq=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.Na(this.Zq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.Na(this.nextVideo,a,b))};
g.h.TA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.TA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.U("proxyStateChange",a,this.o)}T7.fa.dispose.call(this)};
g.h.W=function(){GGa(this);this.B=null;this.D.clear();S7(this,null);T7.fa.W.call(this)};
g.h.Iy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.SD(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.gT=function(a,b){this.U(a,b)};
g.h.KQ=function(a){if(!a)this.Hn(null),S7(this,null);else if(this.C.receiver.volume){a=this.C.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.Hn=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),HGa(this),this.U("remotePlayerChange")};
g.h.JQ=function(a){a?(HGa(this),this.U("remotePlayerChange")):this.Hn(null)};
g.h.Vx=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.WQ=function(){var a=DGa();a&&S7(this,a)};
g.h.sc=function(a){c7("CP",a)};g.B($7,g.zH);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ba(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ba(k)&&(l.currentIndex=k);c&&(this.kb.listId=c);this.kb.videoId=d;this.kb.index=k||0;this.kb.state=3;O7(this.kb,m);this.B="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.ih(l));this.o.connect({method:"setPlaylist",
params:g.ih(l)},a,fFa())}else a8("Connecting without params"),this.o.connect({},a,fFa());JGa(this)};
g.h.dispose=function(){this.la()||(this.U("beforeDispose"),b8(this,3));$7.fa.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.vF(this.J);this.J=NaN;g.vF(this.K);this.K=NaN;this.C=null;g.jH(this.O);this.O.length=0;this.o.dispose();$7.fa.W.call(this);this.B=this.G=this.A=this.kb=this.o=null};
g.h.gL=function(){this.F(2)};
g.h.OQ=function(){a8("Channel opened");this.V&&(this.V=!1,d8(this),this.M=g.tF((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
jFa(TFa(this.o),this.aa)};
g.h.LQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.MQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.V=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.NQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.ih(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.By(a.params.devices);this.A=(0,g.J)(a,function(c){return new f6(c)});
a=!!g.Wa(this.A,function(c){return"LOUNGE_SCREEN"==c.type});
MGa(this,a);break;case "loungeScreenDisconnected":g.gb(this.A,function(c){return"LOUNGE_SCREEN"==c.type});
MGa(this,!1);break;case "remoteConnected":var b=new f6(g.By(a.params.device));g.Wa(this.A,function(c){return b?c.id==b.id:!1})||g.db(this.A,b);
break;case "remoteDisconnected":b=new f6(g.By(a.params.device));g.gb(this.A,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":OGa(this,a);break;case "nowPlaying":QGa(this,a);break;case "onStateChange":PGa(this,a);break;case "onAdStateChange":RGa(this,a);break;case "onVolumeChanged":SGa(this,a);break;case "onSubtitlesTrackChanged":NGa(this,a);break;case "nowAutoplaying":TGa(this,a);break;case "autoplayDismissed":this.U("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.U("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.U("autoplayModeChange",this.B);"DISABLED"==this.B&&this.U("autoplayDismissed");break;case "onHasPreviousNextChanged":UGa(this,a);break;case "requestAssistedSignIn":this.U("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.oV=function(){if(this.C){var a=this.C;this.C=null;this.kb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Fk;$7.prototype.ia=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ia;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.U("beforeDisconnect",a);1==a&&r6();UFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.ea=function(){var a=this.kb;this.C&&(a=this.kb.clone(),Q7(a,this.C,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.ea;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.kb.videoId&&(this.C=b.videoId,g.vF(this.J),this.J=g.tF((0,g.A)(this.oV,this),5E3));var c=[];this.kb.listId==b.listId&&this.kb.videoId==b.videoId&&this.kb.index==b.index||c.push("remoteQueueChange");this.kb.playerState==b.playerState&&this.kb.volume==b.volume&&this.kb.muted==b.muted&&P7(this.kb)==P7(b)&&g.ih(this.kb.o)==g.ih(b.o)||c.push("remotePlayerChange");this.kb.reset(a);(0,g.C)(c,function(d){this.U(d)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Y=function(){var a=this.o.F.id,b=g.Wa(this.A,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Y;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.ba=function(){return this.B||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.ba;$7.prototype.ga=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.ga;$7.prototype.xa=function(){if(!isNaN(this.H())){var a=this.o.A;g.Gv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.xa;$7.prototype.ka=function(a,b){f8(this,a,b);LGa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.ye=function(a){return this.jd.$_gs(a)};
g.h.contains=function(a){return!!this.jd.$_c(a)};
g.h.get=function(a){return this.jd.$_g(a)};
g.h.start=function(){this.jd.$_st()};
g.h.add=function(a,b,c){this.jd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.jd.$_r(a,b,c)};
g.h.Yr=function(a,b,c,d){this.jd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.jd.$_ubk(this.A[a]);this.A.length=0;this.jd=null;g8.fa.W.call(this)};
g.h.EW=function(){this.U("screenChange")};
g.h.FS=function(){this.U("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.FW;p7.prototype.$_gsppc=p7.prototype.ZG;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.Yr;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.ye;p7.prototype.$_gos=p7.prototype.YG;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Fk;var h8=null,i8=null,x8=null,m8=[];g.t(y8,g.K);g.h=y8.prototype;
g.h.W=function(){g.K.prototype.W.call(this);this.B.stop();this.F.stop();this.L.stop();this.V();this.o.unsubscribe("proxyStateChange",this.QE,this);this.o.unsubscribe("remotePlayerChange",this.Kn,this);this.o.unsubscribe("remoteQueueChange",this.Tq,this);this.o.unsubscribe("autoplayUpNext",this.nE,this);this.o.unsubscribe("previousNextChange",this.NE,this);this.o.unsubscribe("nowAutoplaying",this.FE,this);this.o.unsubscribe("autoplayDismissed",this.mE,this);this.o=this.D=null};
g.h.qD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).sb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Jm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.IQ=function(a){this.L.bL(a)};
g.h.hW=function(a){this.qD("control_subtitles_set_track",g.ec(a)?null:a)};
g.h.nG=function(){var a=this.A.getOption("captions","track");g.ec(a)||C8(this,a)};
g.h.BE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Kn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.M.start();this.o.subscribe("remotePlayerChange",this.Kn,this)}};
g.h.YR=function(){g.ec(this.G)||fHa(this,this.G);this.H=!1};
g.h.QE=function(a,b){this.F.stop();2==b&&this.lG()};
g.h.Kn=function(){if(B8(this)){this.B.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.jl(1);break;case 1082:case 1083:this.D.jl(0);break;default:this.D.jl(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.IQ(8));this.kG();break;case 1085:case 3:A8(this,new g.IQ(9));break;case 1083:case 0:A8(this,new g.IQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.IQ(4));break;case 2:A8(this,new g.IQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.IQ(64));break;case -1E3:A8(this,new g.IQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.G=a,fHa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.M.isActive()||this.LG()}else eHa(this)};
g.h.NE=function(){this.A.U("mdxpreviousnextchange")};
g.h.Tq=function(){B8(this)||eHa(this)};
g.h.cK=function(){this.o.TA()};
g.h.nE=function(a){a&&(a=g.hG("/watch_queue_ajax",{method:"GET",ad:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.qU,this)}))&&(this.V=(0,g.A)(a.abort,a))};
g.h.qU=function(a,b){var c=new g.BP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.U("mdxautoplayupnext",c)};
g.h.FE=function(a){isNaN(a)||this.A.U("mdxnowautoplaying",a)};
g.h.mE=function(){this.A.U("mdxautoplaycanceled")};
g.h.FO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.LG=function(){if(B8(this)){var a=U7(this.o);this.C.Ka(this.O);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.O=this.C.R(this.A,"onVolumeChange",this.BE)}};
g.h.kG=function(){this.B.stop();if(!this.o.la()){var a=U7(this.o);a.sb()&&A8(this,new g.IQ(8));z8(this,P7(a));this.B.start()}};
g.h.lG=function(){this.F.stop();this.B.stop();var a=this.o.B.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.t(E8,g.W);E8.prototype.F=function(a){hHa(this,a.state)};g.t(F8,g.$W);F8.prototype.M=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.K=g.xb(a,this.G,this),g.aX(this,(0,g.J)(a,this.G)),a=this.B.getOption("remote","currentReceiver"),this.zf(this.G(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.G=function(a){return a.key};
F8.prototype.yf=function(a){return"cast-selector-receiver"==a?"Cast...":this.K[a].name};
F8.prototype.ld=function(a){g.$W.prototype.ld.call(this,a);this.B.setOption("remote","currentReceiver",this.K[a]);this.D.Jb()};g.t(G8,g.mV);g.h=G8.prototype;g.h.create=function(){ZGa(g.fO(g.Y(this.player)));this.D.push(g.AF("yt-remote-before-disconnect",this.EQ,this));this.D.push(g.AF("yt-remote-connection-change",this.pT,this));this.D.push(g.AF("yt-remote-receiver-availability-change",this.OE,this));this.D.push(g.AF("yt-remote-auto-connect",this.nT,this));this.D.push(g.AF("yt-remote-receiver-resumed",this.mT,this));this.OE()};
g.h.load=function(){this.player.cancelPlayback();g.mV.prototype.load.call(this);this.B=new y8(this,this.player,this.o);var a=(a=dHa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.He(a);gHa(this,this.vn,this.vn);g.D0(this.player.app,6)};
g.h.unload=function(){this.player.U("mdxautoplaycanceled");this.C=this.A;g.Qf(this.B,this.o);this.o=this.B=null;g.mV.prototype.unload.call(this);g.D0(this.player.app,5)};
g.h.W=function(){g.BF(this.D);g.mV.prototype.W.call(this)};
g.h.Vh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.qD.apply(this.B,[a].concat(g.ea(c)))};
g.h.jl=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.VK=function(){return this.loaded?this.B.suggestion:null};
g.h.Yf=function(){return this.o?U7(this.o).Yf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.He=function(a,b){this.J=a||0;this.player.U("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Jc():!a.isAdPlaying()&&this.player.Jc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.C+N7(a):a.C,isAtLiveHead:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.B?a.B+N7(a):
a.B}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.Zq=function(){this.o&&this.o.Zq()};
g.h.EQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.pT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.C;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.C=b,this.load())}else g.Pf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.U("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.OE=function(){this.F=[this.A].concat(aHa());var a=s8()||this.A;H8(this,a);this.player.Ba("onMdxReceiversChange")};
g.h.nT=function(){var a=s8();H8(this,a)};
g.h.mT=function(){this.C=s8()};
g.h.Fc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.C:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.Vx=function(){this.o.Vx()};
g.h.uc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.WZ.remote=G8;})(_yt_player);
