(function(g){var window=this;var KEa=function(a,b){return g.$b(a,b)},c6=function(a){g.Zn(a,"zx",g.Ac());
return a},d6=function(a,b,c){g.Ia(c)||(c=[String(c)]);
g.bo(a.o,b,c)},LEa=function(a,b){var c=[];
g.Jl(b,function(d){try{var e=g.AE.prototype.A.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ba(e)?g.zE(e)&&c.push(d):c.push(d)},a);
return c},MEa=function(a,b){var c=LEa(a,b);
(0,g.C)(c,function(d){g.AE.prototype.remove.call(this,d)},a)},NEa=function(a){if(a.Md){if(a.Md.locationOverrideToken)return{locationOverrideToken:a.Md.locationOverrideToken};
if(null!=a.Md.latitudeE7&&null!=a.Md.longitudeE7)return{latitudeE7:a.Md.latitudeE7,longitudeE7:a.Md.longitudeE7}}return null},OEa=function(a,b,c,d){var e=new g.Qn(null,void 0);
a&&g.Rn(e,a);b&&g.Sn(e,b);c&&g.Tn(e,c);d&&g.Un(e,d);return e},e6=function(a,b){g.tF[a]=!0;
var c=g.rF();c&&c.publish.apply(c,arguments);g.tF[a]=!1},f6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.B=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Kn;this.o=this.A="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",PEa(this,a.capabilities||""),QEa(this,a.experiments||""),this.A=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},PEa=function(a,b){a.capabilities.clear();
(0,g.te)(b.split(","),g.Oa(KEa,REa)).forEach(function(c){a.capabilities.add(c)})},QEa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},g6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},h6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},SEa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},TEa=function(a){return new g6(a)},UEa=function(a){return g.Ia(a)?(0,g.J)(a,TEa):[]},i6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},j6=function(a){return g.Ia(a)?"["+(0,g.J)(a,i6).join(",")+"]":"null"},k6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},VEa=function(a){return(0,g.J)(a,function(b){return{key:b.id,
name:b.name}})},l6=function(a,b){return g.Wa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},m6=function(a,b){return g.Wa(a,function(c){return h6(c,b)})},WEa=function(){var a=(0,g.GI)();
a&&MEa(a,a.o.de(!0))},n6=function(){var a=g.JI("yt-remote-connected-devices")||[];
g.ub(a);return a},XEa=function(a){if(g.bb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.J)(a,function(d,e){return 0==e?d:d.substring(c.length)})},YEa=function(a){g.II("yt-remote-connected-devices",a,86400)},p6=function(){if(o6)return o6;
var a=g.JI("yt-remote-device-id");a||(a=k6(),g.II("yt-remote-device-id",a,31536E3));for(var b=n6(),c=1,d=a;g.ab(b,d);)c++,d=a+"#"+c;return o6=d},q6=function(){var a=n6(),b=p6();
g.ab(a,b);g.LI()&&g.wb(a,b);a=XEa(a);if(g.bb(a))try{g.hI("remote_sid")}catch(c){}else try{g.gI("remote_sid",a.join(","),-1)}catch(c){}},ZEa=function(){return g.JI("yt-remote-session-browser-channel")},$Ea=function(){return g.JI("yt-remote-local-screens")||[]},aFa=function(){g.II("yt-remote-lounge-token-expiration",!0,86400)},bFa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.J)($Ea(),function(d){return d.loungeToken}),c=(0,g.J)(a,function(d){return d.loungeToken});
(0,g.Hj)(c,function(d){return!g.ab(b,d)})&&aFa();
g.II("yt-remote-local-screens",a,31536E3)},cFa=function(a,b){g.II("yt-remote-session-browser-channel",a);
g.II("yt-remote-session-screen-id",b);var c=n6(),d=p6();g.ab(c,d)||c.push(d);YEa(c);q6()},r6=function(a){a||(g.KI("yt-remote-session-screen-id"),g.KI("yt-remote-session-video-id"));
q6();a=n6();g.fb(a,p6());YEa(a)},dFa=function(){if(!s6){var a=g.LE();
a&&(s6=new g.uE(a))}return s6?!!s6.get("yt-remote-use-staging-server"):!1},t6=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},eFa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},u6=function(a){a.length?fFa(a.shift(),function(){u6(a)}):v6()},gFa=function(a){return"chrome-extension://"+a+w6},fFa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},v6=function(){var a=eFa();
a&&a(!1,"No cast extension found")},iFa=function(){if(hFa){var a=2,b=eFa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;fFa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",v6,c)}},jFa=function(){iFa();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);u6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+w6,"//www.gstatic.com/eureka/clank"+w6])},x6=function(a,b,c){g.K.call(this);
this.F=null!=c?(0,g.A)(a,c):a;this.Gd=b;this.D=(0,g.A)(this.aL,this);this.o=!1;this.A=0;this.B=this.Ga=null;this.C=[]},y6=function(){},z6=function(a,b,c,d){this.o=a;
this.B=b;this.G=c;this.F=d||1;this.C=45E3;this.Y=new g.go(this);this.A=new g.dh;this.A.setInterval(250)},lFa=function(a,b,c){a.ek=1;
a.Bh=c6(b.clone());a.mj=c;a.D=!0;kFa(a,null)},A6=function(a,b,c,d,e){a.ek=1;
a.Bh=c6(b.clone());a.mj=null;a.D=c;e&&(a.KF=!1);kFa(a,d)},kFa=function(a,b){a.Yk=(0,g.H)();
B6(a);a.ci=a.Bh.clone();d6(a.ci,"t",a.F);a.ko=0;a.Xc=a.o.Yt(a.o.Yn()?b:null);0<a.Gu&&(a.sr=new g.tm((0,g.A)(a.SG,a,a.Xc),a.Gu));a.Y.X(a.Xc,"readystatechange",a.eV);var c=a.Mi?g.jc(a.Mi):{};a.mj?(a.os="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Xc.send(a.ci,a.os,a.mj,c)):(a.os="GET",a.KF&&!g.he&&(c.Connection="close"),a.Xc.send(a.ci,a.os,null,c));a.o.Bf(1)},oFa=function(a,b,c){for(var d=!0;!a.si&&a.ko<c.length;){var e=mFa(a,c);
if(e==C6){4==b&&(a.Ch=4,D6(15),d=!1);break}else if(e==nFa){a.Ch=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Ch=1,D6(17),d=!1);a.Hf=a.Hf&&d;d||(F6(a),G6(a))},mFa=function(a,b){var c=a.ko,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return nFa;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.ko=d+c;return e},qFa=function(a,b){a.Yk=(0,g.H)();
B6(a);var c=b?window.location.hostname:"";a.ci=a.Bh.clone();g.Zn(a.ci,"DOMAIN",c);g.Zn(a.ci,"t",a.F);try{a.Jf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Ch=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in pFa)k=H6[l]=pFa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Gd(g.Wc("b/12014412"),d+"</body></html>");a.Jf.open();a.Jf.write(g.xd(c));a.Jf.close();a.Jf.parentWindow.m=(0,g.A)(a.mU,a);a.Jf.parentWindow.d=(0,g.A)(a.ZE,a,!0);a.Jf.parentWindow.rpcClose=(0,g.A)(a.ZE,a,!1);c=a.Jf.createElement("DIV");a.Jf.parentWindow.document.body.appendChild(c);d=g.kd(a.ci.toString());d=g.uc(g.hd(d));d=g.Gd(g.Wc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Hd(c,d);a.o.Bf(1)},B6=function(a){a.By=(0,g.H)()+a.C;
rFa(a,a.C)},rFa=function(a,b){if(null!=a.zl)throw Error("WatchDog timer not null");
a.zl=I6((0,g.A)(a.BU,a),b)},J6=function(a){a.zl&&(g.x.clearTimeout(a.zl),a.zl=null)},G6=function(a){a.o.NB()||a.si||a.o.Tq(a)},F6=function(a){J6(a);
g.Qf(a.sr);a.sr=null;a.A.stop();g.mo(a.Y);if(a.Xc){var b=a.Xc;a.Xc=null;b.abort();b.dispose()}a.Jf&&(a.Jf=null)},E6=function(a,b){try{a.o.SE(a,b),a.o.Bf(4)}catch(c){}},tFa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;sFa(a,b,function(k){k?c(!0):g.x.setTimeout(function(){tFa(a,b,c,d,f)},f)})}},sFa=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},uFa=function(a){this.o=a;
this.A=new y6},vFa=function(a){var b=L6(a.o,a.Pl,"/mail/images/cleardot.gif");
c6(b);tFa(b.toString(),5E3,(0,g.A)(a.aK,a),3,2E3);a.Bf(1)},N6=function(a){var b=a.o.J;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.oe=new z6(a,void 0,void 0,void 0),a.oe.Mi=a.Eu,b=a.o,b=L6(b,b.Yn()?a.Im:null,a.Fu),D6(5),!g.fe||g.Oc(10))d6(b,"TYPE","xmlhttp"),A6(a.oe,b,!1,a.Im,!1);else{d6(b,"TYPE","html");var c=a.oe;a=!!a.Im;c.ek=3;c.Bh=c6(b.clone());qFa(c,a)}},O6=function(a,b,c){this.o=1;
this.A=[];this.C=[];this.D=new y6;this.H=a||null;this.J=null!=b?b:null;this.F=c||!1},wFa=function(a,b){this.o=a;
this.map=b;this.context=null},xFa=function(a){g.Sf.call(this,"statevent",a)},yFa=function(a,b){g.Sf.call(this,"timingevent",a);
this.size=b},zFa=function(a){g.Sf.call(this,"serverreachability",a)},CFa=function(a){AFa(a);
if(3==a.o){var b=a.An++,c=a.zp.clone();g.Zn(c,"SID",a.B);g.Zn(c,"RID",b);g.Zn(c,"TYPE","terminate");P6(a,c);b=new z6(a,a.B,b,void 0);b.ek=2;b.Bh=c6(c.clone());(new Image).src=b.Bh;b.Yk=(0,g.H)();B6(b)}BFa(a)},DFa=function(a){a.wK(1,0);
a.zp=L6(a,null,a.Du);Q6(a)},AFa=function(a){a.rh&&(a.rh.abort(),a.rh=null);
a.Bc&&(a.Bc.cancel(),a.Bc=null);a.Dg&&(g.x.clearTimeout(a.Dg),a.Dg=null);R6(a);a.ie&&(a.ie.cancel(),a.ie=null);a.vh&&(g.x.clearTimeout(a.vh),a.vh=null)},EFa=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.A.push(new wFa(a.YP++,b));2!=a.o&&3!=a.o||Q6(a)},Q6=function(a){a.ie||a.vh||(a.vh=I6((0,g.A)(a.YE,a),0),a.Vj=0)},GFa=function(a,b){if(1==a.o){if(!b){a.An=Math.floor(1E5*Math.random());
var c=a.An++,d=new z6(a,"",c,void 0);d.Mi=null;var e=S6(a),f=a.zp.clone();g.Zn(f,"RID",c);g.Zn(f,"CVER","1");P6(a,f);lFa(d,f,e);a.ie=d;a.o=2}}else 3==a.o&&(b?FFa(a,b):0==a.A.length||a.ie||FFa(a))},FFa=function(a,b){if(b)if(6<a.xi){a.A=a.C.concat(a.A);
a.C.length=0;var c=a.An-1;var d=S6(a)}else c=b.G,d=b.mj;else c=a.An++,d=S6(a);var e=a.zp.clone();g.Zn(e,"SID",a.B);g.Zn(e,"RID",c);g.Zn(e,"AID",a.yk);P6(a,e);c=new z6(a,a.B,c,a.Vj+1);c.Mi=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ie=c;lFa(c,e,d)},P6=function(a,b){if(a.Fd){var c=a.Fd.tB();
c&&g.Ob(c,function(d,e){g.Zn(b,e,d)})}},S6=function(a){var b=Math.min(a.A.length,1E3),c=["count="+b];
if(6<a.xi&&0<b){var d=a.A[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.A[e].o,k=a.A[e].map;f=6>=a.xi?e:f-d;try{g.Ob(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.A.splice(0,b));
return c.join("&")},HFa=function(a){a.Bc||a.Dg||(a.G=1,a.Dg=I6((0,g.A)(a.XE,a),0),a.Lj=0)},T6=function(a){if(a.Bc||a.Dg||3<=a.Lj)return!1;
a.G++;a.Dg=I6((0,g.A)(a.XE,a),IFa(a,a.Lj));a.Lj++;return!0},M6=function(a,b,c){a.ks=c;
a.Uf=b.Rg;a.F||DFa(a)},R6=function(a){null!=a.Ai&&(g.x.clearTimeout(a.Ai),a.Ai=null)},IFa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},U6=function(a,b){if(2==b||9==b){var c=null;
a.Fd&&(c=null);var d=(0,g.A)(a.VV,a);c||(c=new g.Qn("//www.google.com/images/cleardot.gif"),c6(c));sFa(c.toString(),1E4,d)}else D6(2);JFa(a,b)},JFa=function(a,b){a.o=0;
a.Fd&&a.Fd.sA(b);BFa(a);AFa(a)},BFa=function(a){a.o=0;
a.Uf=-1;if(a.Fd)if(0==a.C.length&&0==a.A.length)a.Fd.Lt();else{g.kb(a.C);var b=g.kb(a.A);a.C.length=0;a.A.length=0;a.Fd.Lt(b)}},L6=function(a,b,c){var d=g.$n(c);
if(""!=d.A)b&&g.Sn(d,b+"."+d.A),g.Tn(d,d.D);else{var e=window.location;d=OEa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.jm&&g.Ob(a.jm,function(f,k){g.Zn(d,k,f)});
g.Zn(d,"VER",a.xi);P6(a,d);return d},I6=function(a,b){if(!g.Ka(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},D6=function(a){V6.dispatchEvent(new xFa(V6,a))},KFa=function(){},LFa=function(a,b){this.action=a;
this.params=b||{}},W6=function(a,b){g.K.call(this);
this.o=new g.V(this.cU,0,this);g.L(this,this.o);this.Gd=5E3;this.A=0;if(g.Ka(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ka(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},X6=function(a,b,c){this.K=a;
this.F=b;this.B=new g.tE;this.A=new W6(this.zW,this);this.o=this.ob=null;this.Bb=!1;this.D=null;this.J="";this.H=this.C=0;this.G=[];this.L=c||!1},MFa=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.ks,sessionId:a.o.B,arrayId:a.o.yk}},NFa=function(a,b){a.H=b||0;
a.A.stop();a.o&&(3==a.o.o&&GFa(a.o),CFa(a.o));a.H=0},Y6=function(a){return!!a.o&&3==a.o.o},OFa=function(a,b){(a.F.loungeIdToken=b)||a.A.stop()},Z6=function(a){this.port=this.domain="";
this.o="/api/lounge";this.A=!0;a=a||document.location.href;var b=g.sh(a)||"";b&&(this.port=":"+b);this.domain=g.rh(a)||"";a=g.Mb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Kb(a,"10.0")&&(this.A=!1))},$6=function(a,b){var c=a.o;
if(g.Ba(void 0)?0:a.A)c="https://"+a.domain+a.port+a.o;return g.Bh(c+b,{})},a7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Oa(a.C,d,!0),onError:g.Oa(a.B,e),Jd:g.Oa(a.D,e)};c&&(a.Sb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.cG(b,a)},SFa=function(){var a=PFa;
QFa();b7.push(a);RFa(b7)},c7=function(a,b){QFa();
var c=b7,d=TFa(a,String(b));g.bb(c)?UFa(d):(RFa(c),(0,g.C)(c,function(e){e(d)}))},QFa=function(){b7||(b7=g.y("yt.mdx.remote.debug.handlers_")||[],g.Ea("yt.mdx.remote.debug.handlers_",b7,void 0))},UFa=function(a){var b=(d7+1)%50;
d7=b;e7[b]=a;f7||(f7=49==b)},RFa=function(a){var b=e7;
if(b[0]){var c=d7,d=f7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(f){f(e)})}while(d!=c);
e7=Array(50);d7=-1;f7=!1}},TFa=function(a,b){var c=((0,g.H)()-VFa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},g7=function(a){g.uH.call(this);
this.G=a;this.o=[]},WFa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},XFa=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.te)(a.o,function(f){return!!l6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=WFa(a,b[d])||c;return c},YFa=function(a,b){var c=a.o.length;
a.o=(0,g.te)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},h7=function(a,b,c,d){g.uH.call(this);
this.F=a;this.D=b;this.B=c;this.C=d;this.A=0;this.o=null;this.Ga=NaN},j7=function(a){g7.call(this,"LocalScreenService");
this.B=a;this.A=NaN;i7(this);this.info("Initializing with "+j6(this.o))},ZFa=function(a){if(a.o.length){var b=(0,g.J)(a.o,function(d){return d.id}),c=$6(a.B,"/pairing/get_lounge_token_batch");
a7(a.B,c,{screen_ids:b.join(",")},(0,g.A)(a.oL,a),(0,g.A)(a.nL,a))}},i7=function(a){var b=UEa($Ea());
b=(0,g.te)(b,function(c){return!c.uuid});
return XFa(a,b)},k7=function(a,b){bFa((0,g.J)(a.o,SEa));
b&&aFa()},m7=function(a,b){g.uH.call(this);
this.F=b;var c=g.JI("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.ab(c,l)}this.o=d;this.D=a;this.B=this.C=NaN;this.A=null;l7("Initialized with "+g.jh(this.o))},$Fa=function(a,b,c){var d=$6(a.D,"/pairing/get_screen_availability");
a7(a.D,d,{lounge_token:b.token},(0,g.A)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},n7=function(a,b){a:if(g.Ub(b)!=g.Ub(a.o))var c=!1;
else{c=g.Xb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(l7("Updated online screens: "+g.jh(a.o)),a.o=b,a.V("screenChange"));aGa(a)},o7=function(a){isNaN(a.B)||g.qF(a.B);
a.B=g.oF((0,g.A)(a.ox,a),0<a.C&&a.C<(0,g.H)()?2E4:1E4)},l7=function(a){c7("OnlineScreenService",a)},bGa=function(a){var b={};
(0,g.C)(a.F(),function(c){c.token?b[c.token]=c.id:this.sc("Requesting availability of screen w/o lounge token.")});
return b},aGa=function(a){a=g.Xb(g.Qb(a.o,function(b){return b}));
g.ub(a);a.length?g.II("yt-remote-online-screen-ids",a.join(","),60):g.KI("yt-remote-online-screen-ids")},p7=function(a){g7.call(this,"ScreenService");
this.F=a;this.A=this.B=null;this.C=[];this.D={};cGa(this)},eGa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var k=a.ze();if(k=(c?m6(k,c):null)||m6(k,b)){k.uuid=b;var l=q7(a,k);$Fa(a.A,l,function(m){e(m?l:null)})}else c?dGa(a,c,(0,g.A)(function(m){var n=q7(this,new g6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));$Fa(this.A,n,function(p){e(p?n:null)})},a),f):e(null)},fGa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},dGa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Sb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.cG($6(a.F,"/pairing/get_lounge_token_batch"),e)},gGa=function(a){a.o=a.B.ze();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+j6(a.o))},cGa=function(a){r7(a);
a.B=new j7(a.F);a.B.subscribe("screenChange",(0,g.A)(a.BL,a));gGa(a);a.C=UEa(g.JI("yt-remote-automatic-screen-cache")||[]);r7(a);a.info("Initializing automatic screens: "+j6(a.C));a.A=new m7(a.F,(0,g.A)(a.ze,a,!0));a.A.subscribe("screenChange",(0,g.A)(function(){this.V("onlineScreenChange")},a))},q7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=m6(a.C,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.C.push(b),g.II("yt-remote-automatic-screen-cache",(0,g.J)(a.C,SEa)));r7(a);a.D[b.uuid]=b.id;g.II("yt-remote-device-id-map",a.D,31536E3);return b},r7=function(a){a.D=g.JI("yt-remote-device-id-map")||{}},s7=function(a,b,c){g.uH.call(this);
this.R=c;this.J=a;this.A=b;this.B=null},t7=function(a,b){c7(a.R,b)},u7=function(a,b){s7.call(this,a,b,"CastSession");
this.o=null;this.C=0;this.F=(0,g.A)(this.GW,this);this.D=(0,g.A)(this.NU,this);this.C=g.oF((0,g.A)(function(){hGa(this,null)},this),12E4)},iGa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.jh(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.z,(0,g.A)(function(){t7(this,"Failed to send message: getMdxSessionStatus.")},a)):t7(a,"Sending yt message without session: "+g.jh(b))},hGa=function(a,b){g.qF(a.C);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.B||a.B.id!=b){var c=(0,g.A)(a.Uq,a),d=(0,g.A)(a.Ee,a);a.EB(b,c,d,5)}}else a.Ee(Error("Waiting for session status timed out."))},v7=function(a,b,c){s7.call(this,a,b,"DialSession");
this.C=this.H=null;this.K="";this.N=c;this.D=null;this.G=g.z;this.F=NaN;this.L=(0,g.A)(this.JW,this);this.o=g.z},jGa=function(a){a.o=a.J.WG(a.K,a.A.label,a.A.friendlyName,(0,g.A)(function(b){this.o=g.z;
this.Uq(b)},a),(0,g.A)(function(b){this.o=g.z;
this.Ee(b)},a))},kGa=function(a){var b={};
b.pairingCode=a.K;b.theme=a.N;if(a.D){var c=a.D.currentTime||0;b.v=a.D.videoId;b.t=c}dFa()&&(b.env_useStageMdx=1);return g.zh(b)},w7=function(a,b){s7.call(this,a,b,"ManualSession");
this.o=g.oF((0,g.A)(this.Ak,this,null),150)},x7=function(a,b,c,d){g.uH.call(this);
this.A=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.D=!1;this.B=[];this.C=(0,g.A)(this.iT,this)},lGa=function(a,b){return b?g.Wa(a.B,function(c){return h6(b,c.label)},a):null},y7=function(a){c7("Controller",a)},PFa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},z7=function(a){return a.D||!!a.B.length||!!a.o},A7=function(a,b,c){b!=a.o&&(g.Qf(a.o),(a.o=b)?(c?a.V("yt-remote-cast2-receiver-resumed",b.A):a.V("yt-remote-cast2-receiver-selected",
b.A),b.subscribe("sessionScreen",(0,g.A)(a.VE,a,b)),b.B?a.V("yt-remote-cast2-session-change",b.B):c&&a.o.Ak(null)):a.V("yt-remote-cast2-session-change",null))},mGa=function(a){var b=a.A.VG(),c=a.o&&a.o.A;
a=(0,g.J)(b,function(d){c&&h6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=lGa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},sGa=function(a,b,c,d,e,f,k){nGa()?oGa(b,e,f,k)&&(C7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?pGa(a,c):(window.__onGCastApiAvailable=function(l,m){l?pGa(a,c):(D7("Failed to load cast API: "+m),E7(!1),C7(!1),g.KI("yt-remote-cast-available"),g.KI("yt-remote-cast-receiver"),qGa(),c(!1))},d?g.BF("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?jFa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?v6():(iFa(),u6(rGa.map(gFa))))):B7("Cannot initialize because not running Chrome")},qGa=function(){B7("dispose");
var a=F7();a&&a.dispose();g.Ea("yt.mdx.remote.cloudview.instance_",null,void 0);tGa(!1);g.wF(G7);G7.length=0},H7=function(){return!!g.JI("yt-remote-cast-installed")},uGa=function(){var a=g.JI("yt-remote-cast-receiver");
return a?a.friendlyName:null},vGa=function(){B7("clearCurrentReceiver");
g.KI("yt-remote-cast-receiver")},wGa=function(){return H7()?F7()?F7().getCastSession():(D7("getCastSelector: Cast is not initialized."),null):(D7("getCastSelector: Cast API is not installed!"),null)},J7=function(){H7()?F7()?I7()?(B7("Requesting cast selector."),F7().requestSession()):(B7("Wait for cast API to be ready to request the session."),G7.push(g.vF("yt-remote-cast2-api-ready",J7))):D7("requestCastSelector: Cast is not initialized."):D7("requestCastSelector: Cast API is not installed!")},K7=
function(a,b){I7()?F7().setConnectedScreenStatus(a,b):D7("setConnectedScreenStatus called before ready.")},nGa=function(){var a=0<=g.Mb.search(/ (CrMo|Chrome|CriOS)\//);
return g.kM||a},xGa=function(a,b){F7().init(a,b)},oGa=function(a,b,c,d){var e=!1;
F7()||(a=new x7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.II("yt-remote-cast-available",f);e6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){B7("onReceiverSelected: "+f.friendlyName);
g.II("yt-remote-cast-receiver",f);e6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){B7("onReceiverResumed: "+f.friendlyName);
g.II("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){B7("onSessionChange: "+i6(f));
f||g.KI("yt-remote-cast-receiver");e6("yt-remote-cast2-session-change",f)}),g.Ea("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
B7("cloudview.createSingleton_: "+e);return e},F7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},pGa=function(a,b){E7(!0);
C7(!1);xGa(a,function(c){c?(tGa(!0),g.yF("yt-remote-cast2-api-ready")):(D7("Failed to initialize cast API."),E7(!1),g.KI("yt-remote-cast-available"),g.KI("yt-remote-cast-receiver"),qGa());b(c)})},B7=function(a){c7("cloudview",a)},D7=function(a){c7("cloudview",a)},E7=function(a){B7("setCastInstalled_ "+a);
g.II("yt-remote-cast-installed",a)},I7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},tGa=function(a){B7("setApiReady_ "+a);
g.Ea("yt.mdx.remote.cloudview.apiReady_",a,void 0)},C7=function(a){g.Ea("yt.mdx.remote.cloudview.initializing_",a,void 0)},L7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.Yf=!1;this.J=this.H=this.A=this.C=0;this.B=NaN;this.D=!1;this.reset(a)},M7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.Yf=!1;a.hasNext=!1;a.G=0;a.F=(0,g.H)();a.C=0;a.A=0;a.H=0;a.J=0;a.B=NaN;a.D=!1},N7=function(a){return a.tb()?((0,g.H)()-a.F)/1E3:0},O7=function(a,b){a.G=b;
a.F=(0,g.H)()},P7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.H)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},Q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&M7(a)},R7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.kc(a.o);b.hasPrevious=a.Yf;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.A;b.duration=a.H;b.loadedTime=a.J;b.liveIngestionTime=a.B;return b},T7=function(a,b){g.uH.call(this);
this.o=0;this.C=a;this.F=[];this.D=new g.KD;this.B=this.A=null;this.J=(0,g.A)(this.JQ,this);this.G=(0,g.A)(this.En,this);this.H=(0,g.A)(this.IQ,this);this.K=(0,g.A)(this.VQ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Jy,this),yGa(this))):c=3;0!=c&&(b?this.Jy(c):g.oF((0,g.A)(function(){this.Jy(c)},this),0));
var d=wGa();d&&S7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},U7=function(a){return new L7(a.C.getPlayerContextData())},yGa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.C.subscribe(b,g.Oa(this.eT,b),this))},a)},zGa=function(a){(0,g.C)(a.F,function(b){this.C.unsubscribeByKey(b)},a);
a.F.length=0},V7=function(a,b){50>a.D.Jc()&&g.MD(a.D,b)},X7=function(a,b,c){var d=U7(a);
O7(d,c);-1E3!=d.playerState&&(d.playerState=b);W7(a,d)},Y7=function(a,b,c){a.C.sendMessage(b,c)},W7=function(a,b){zGa(a);
a.C.setPlayerContextData(R7(b));yGa(a)},S7=function(a,b){a.B&&(a.B.removeUpdateListener(a.J),a.B.removeMediaListener(a.G),a.En(null));
a.B=b;a.B&&(c7("CP","Setting cast session: "+a.B.sessionId),a.B.addUpdateListener(a.J),a.B.addMediaListener(a.G),a.B.media.length&&a.En(a.B.media[0]))},AGa=function(a){var b=a.A.media,c=a.A.customData;
if(b&&c){var d=U7(a);b.contentId!=d.videoId&&c7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;O7(d,a.A.getEstimatedTime());W7(a,d)}else c7("CP","No cast media video. Ignoring state update.")},Z7=function(a,b,c){return(0,g.A)(function(d){this.sc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.sc("Retrying "+b+" using MDx browser channel."),Y7(this,b,c))},a)},$7=function(a,b,c){g.uH.call(this);
this.D=NaN;this.N=!1;this.K=this.J=this.L=this.R=NaN;this.T=[];this.C=this.G=this.B=this.qb=this.o=null;this.ua=a;this.T.push(g.dH(window,"beforeunload",(0,g.A)(this.eL,this)));this.A=[];this.qb=new L7;this.aa=b.id;this.o=BGa(this,c);this.o.subscribe("handlerOpened",this.NQ,this);this.o.subscribe("handlerClosed",this.KQ,this);this.o.subscribe("handlerError",this.LQ,this);this.o.subscribe("handlerMessage",this.MQ,this);OFa(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.qb.videoId;
g.LI()&&g.II("yt-remote-session-video-id",d)},this)},a8=function(a){c7("conn",a)},BGa=function(a,b){return new X6($6(a.ua,"/bc"),b)},b8=function(a,b){a.V("proxyStateChange",b)},CGa=function(a){a.D=g.oF((0,g.A)(function(){a8("Connecting timeout");
this.F(1)},a),2E4)},c8=function(a){g.qF(a.D);
a.D=NaN},d8=function(a){g.qF(a.R);
a.R=NaN},DGa=function(a){e8(a);
a.L=g.oF((0,g.A)(function(){f8(this,"getNowPlaying")},a),2E4)},e8=function(a){g.qF(a.L);
a.L=NaN},FGa=function(a,b){b&&(c8(a),d8(a));
b==(Y6(a.o)&&isNaN(a.D))?b&&(b8(a,1),f8(a,"getSubtitlesTrack")):b?(a.Z()&&a.qb.reset(),b8(a,1),f8(a,"getNowPlaying"),EGa(a)):a.F(1)},GGa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.qb.videoId&&(g.ec(b.params)?a.qb.o=null:a.qb.o=b.params,a.V("remotePlayerChange"))},HGa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.qb.listId=b.params.listId||a.qb.listId;Q7(a.qb,c,d);a.V("remoteQueueChange")},JGa=function(a,b){b.params=b.params||{};
HGa(a,b);IGa(a,b);a.V("autoplayDismissed")},IGa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
O7(a.qb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.qb.playerState&&(c=-1E3);a.qb.playerState=c;c=Number(b.params.loadedTime);a.qb.J=isNaN(c)?0:c;c=Number(b.params.duration);a.qb.H=isNaN(c)?0:c;c=a.qb;var d=Number(b.params.liveIngestionTime);c.B=d;c.D=isNaN(d)?!1:!0;c=a.qb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.A=isNaN(e)?0:e;1==a.qb.playerState?DGa(a):e8(a);a.V("remotePlayerChange")},KGa=function(a,b){if(-1E3!=
a.qb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.qb.playerState=c;c=parseInt(b.params.currentTime,10);O7(a.qb,isNaN(c)?0:c);a.V("remotePlayerChange")}},LGa=function(a,b){var c="true"==b.params.muted;
a.qb.volume=parseInt(b.params.volume,10);a.qb.muted=c;a.V("remotePlayerChange")},MGa=function(a,b){a.G=b.params.videoId;
a.V("nowAutoplaying",parseInt(b.params.timeout,10))},NGa=function(a,b){var c="true"==b.params.hasNext;
a.qb.Yf="true"==b.params.hasPrevious;a.qb.hasNext=c;a.V("previousNextChange")},EGa=function(a){g.qF(a.K);
a.K=g.oF((0,g.A)(a.F,a,1),864E5)},f8=function(a,b,c){c?a8("Sending: action="+b+", params="+g.jh(c)):a8("Sending: action="+b);
a.o.sendMessage(b,c)},g8=function(a){g7.call(this,"ScreenServiceProxy");
this.kd=a;this.A=[];this.A.push(this.kd.$_s("screenChange",(0,g.A)(this.EW,this)));this.A.push(this.kd.$_s("onlineScreenChange",(0,g.A)(this.DS,this)))},SGa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.fF("MDX_CONFIG")||b;WEa();q6();h8||(h8=new Z6(b?b.loungeApiHost:void 0),dFa()&&(h8.o="/api/loungedev"));i8||(i8=g.y("yt.mdx.remote.deferredProxies_")||[],g.Ea("yt.mdx.remote.deferredProxies_",i8,void 0));OGa();var c=j8();if(!c){var d=new p7(h8);g.Ea("yt.mdx.remote.screenService_",d,void 0);c=j8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);sGa(a,d,function(m){m?k8()&&K7(k8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){e6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.Ea("yt.mdx.remote.initialized_",!0,void 0),l8("Initializing: "+g.jh(b)),m8.push(g.vF("yt-remote-cast2-availability-change",function(){e6("yt-remote-receiver-availability-change")})),m8.push(g.vF("yt-remote-cast2-receiver-selected",function(){n8(null);
e6("yt-remote-auto-connect","cast-selector-receiver")})),m8.push(g.vF("yt-remote-cast2-receiver-resumed",function(){e6("yt-remote-receiver-resumed","cast-selector-receiver")})),m8.push(g.vF("yt-remote-cast2-session-change",PGa)),m8.push(g.vF("yt-remote-connection-change",function(m){m?K7(k8(),"YouTube TV"):o8()||(K7(null,null),vGa())})),a=p8(),b.isAuto&&(a.id+="#dial"),g.UF("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),l8(" -- with channel params: "+
g.jh(a)),QGa(a),c.start(),k8()||RGa())},UGa=function(){var a=TGa();
H7()&&g.JI("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},TGa=function(){var a=j8().kd.$_gos();
var b=q8();b&&r8()&&(l6(a,b)||a.push(b));return VEa(a)},s8=function(){var a=VGa();
!a&&H7()&&uGa()&&(a={key:"cast-selector-receiver",name:uGa()});return a},VGa=function(){var a=TGa(),b=q8();
b||(b=o8());return g.Wa(a,function(c){return b&&h6(b,c.key)?!0:!1})},q8=function(){var a=k8();
if(!a)return null;var b=j8().ze();return m6(b,a)},PGa=function(a){l8("remote.onCastSessionChange_: "+i6(a));
if(a){var b=q8();b&&b.id==a.id?K7(b.id,"YouTube TV"):(b&&t8(),u8(a,1))}else r8()&&t8()},t8=function(){I7()?F7().stopSession():D7("stopSession called before API ready.");
var a=r8();a&&(a.disconnect(1),v8(null))},w8=function(){var a=r8();
return!!a&&3!=a.getProxyState()},l8=function(a){c7("remote",a)},j8=function(){if(!x8){var a=g.y("yt.mdx.remote.screenService_");
x8=a?new g8(a):null}return x8},k8=function(){return g.y("yt.mdx.remote.currentScreenId_")},WGa=function(a){g.Ea("yt.mdx.remote.currentScreenId_",a,void 0)},XGa=function(){return g.y("yt.mdx.remote.connectData_")},n8=function(a){g.Ea("yt.mdx.remote.connectData_",a,void 0)},r8=function(){return g.y("yt.mdx.remote.connection_")},v8=function(a){var b=r8();
n8(null);a||WGa("");g.Ea("yt.mdx.remote.connection_",a,void 0);i8&&((0,g.C)(i8,function(c){c(a)}),i8.length=0);
b&&!a?e6("yt-remote-connection-change",!1):!b&&a&&e6("yt-remote-connection-change",!0)},o8=function(){var a=g.LI();
if(!a)return null;var b=j8().ze();return m6(b,a)},u8=function(a,b){q8()&&q8();
WGa(a.id);var c=new $7(h8,a,p8());c.connect(b,XGa());c.subscribe("beforeDisconnect",function(d){e6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){r8()&&v8(null)});
v8(c)},RGa=function(){var a=o8();
a?(l8("Resume connection to: "+i6(a)),u8(a,0)):(r6(),vGa(),l8("Skipping connecting because no session screen found."))},OGa=function(){var a=p8();
if(g.ec(a)){a=p6();var b=g.JI("yt-remote-session-name")||"",c=g.JI("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ea("yt.mdx.remote.channelParams_",a,void 0)}},p8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},QGa=function(a){a?(g.II("yt-remote-session-app",a.app),g.II("yt-remote-session-name",a.name)):(g.KI("yt-remote-session-app"),g.KI("yt-remote-session-name"));
g.Ea("yt.mdx.remote.channelParams_",a,void 0)},y8=function(a,b,c){g.K.call(this);
this.D=a;this.A=b;this.B=new g.rH(this);g.L(this,this.B);this.B.P(b,"onCaptionsTrackListChanged",this.WR);this.B.P(b,"captionschanged",this.HQ);this.B.P(b,"captionssettingschanged",this.nG);this.B.P(b,"videoplayerreset",this.Vq);this.B.P(b,"mdxautoplaycancel",this.ZJ);this.T=this.B.P(b,"onVolumeChange",this.CE);this.H=!1;this.o=c;c.subscribe("proxyStateChange",this.RE,this);c.subscribe("remotePlayerChange",this.Hn,this);c.subscribe("remoteQueueChange",this.Vq,this);c.subscribe("autoplayUpNext",this.oE,
this);c.subscribe("previousNextChange",this.OE,this);c.subscribe("nowAutoplaying",this.GE,this);c.subscribe("autoplayDismissed",this.nE,this);this.suggestion=null;this.J=new g.GQ(64);this.C=new g.V(this.kG,500,this);g.L(this,this.C);this.F=new g.V(this.lG,1E3,this);g.L(this,this.F);this.L=new x6(this.fW,0,this);g.L(this,this.L);this.G={};this.R=new g.V(this.JG,1E3,this);g.L(this,this.R);this.K=new g.tm(this.DO,1E3,this);g.L(this,this.K);this.N=g.z;this.nG();this.Vq();this.Hn()},z8=function(a,b){a.D.Ie(b,
a.A.getVideoData().lengthSeconds)},YGa=function(a){z8(a,0);
a.C.stop();A8(a,new g.GQ(64))},C8=function(a,b){if(B8(a)&&!a.H){var c=null;
b&&(c={style:a.A.getSubtitlesUserSettings()},g.mc(c,b));a.o.YF(a.A.getVideoData(1).videoId,c);a.G=U7(a.o).o}},D8=function(a,b){var c=a.A.getPlaylist();
if(c){var d=c.ye();var e=c.listId.toString()}c=a.A.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.qk,NEa(c));A8(a,new g.GQ(1))},ZGa=function(a,b){if(b){var c=a.A.getOption("captions","tracklist",{I4:1});
c&&c.length?(a.A.setOption("captions","track",b),a.H=!1):(a.A.loadModule("captions"),a.H=!0)}else a.A.setOption("captions","track",{})},B8=function(a){return U7(a.o).videoId==a.A.getVideoData(1).videoId},A8=function(a,b){a.F.stop();
var c=a.J;if(!g.MQ(c,b)){var d=g.X(b,2);d!=g.X(a.J,2)&&g.SU(a.A,d);a.J=b;$Ga(a.D,c,b)}},E8=function(a){g.W.call(this,{I:"div",
M:"ytp-remote",O:[{I:"div",M:"ytp-remote-display-status",O:[{I:"div",M:"ytp-remote-display-status-icon",O:[g.hta()]},{I:"div",M:"ytp-remote-display-status-text",ba:"{{statustext}}"}]}]});this.B=new g.IV(this,250);g.L(this,this.B);this.C=a;this.P(a,"presentingplayerstatechange",this.D);aHa(this,g.OU(a))},aHa=function(a,b){if(3==a.C.getPresentingPlayerType()){var c={RECEIVER_NAME:a.C.getOption("remote","currentReceiver").name};
c=g.X(b,128)?g.vV("Error on $RECEIVER_NAME",c):b.tb()||g.X(b,4)?g.vV("Playing on $RECEIVER_NAME",c):g.vV("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.B.show()}else a.B.hide()},F8=function(a,b){g.ZW.call(this,"Play on",0,a,b);
this.B=a;this.J={};this.P(a,"onMdxReceiversChange",this.L);this.P(a,"presentingplayerstatechange",this.L);this.L()},G8=function(a){g.lV.call(this,a);
this.A={key:k6(),name:"This computer"};this.C=null;this.D=[];this.G=this.o=null;this.F=[this.A];this.B=this.A;this.pn=new g.GQ(64);this.J=0;this.H=-1;if(!g.kO(g.Y(this.player))){a=this.player;var b=g.vQ(a);b&&(b=b.tn())&&(b=new F8(a,b),g.L(this,b));b=new E8(a);g.L(this,b);g.cV(a,b.element,4)}},$Ga=function(a,b,c){a.pn=c;
a.player.V("presentingplayerstatechange",new g.QQ(c,b))},H8=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)t8();
else{a.B=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Ba(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.qk,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=NEa(d))&&(c.locationInfo=d);d=c}else d=null;l8("Connecting to: "+g.jh(b));"cast-selector-receiver"==b.key?
(n8(d||null),I7()?F7().setLaunchParams(d||null):D7("setLaunchParams called before ready.")):!d&&w8()&&k8()==b.key?e6("yt-remote-connection-change",!0):(t8(),n8(d||null),d=j8().ze(),(d=m6(d,b.key))&&u8(d,1))}},pFa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},H6={"'":"\\'"},bHa={},REa={cY:"atp",L2:"ska",Y1:"que",g1:"mus",H2:"sus",q_:"dsp",r2:"seq"};
f6.prototype.sh=function(){var a=new f6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.B=this.B;a.A=this.A;a.o=this.o};
var s6,o6="",w6=t6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",hFa=t6("loadCastFramework")||t6("loadCastApplicationFramework"),rGa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(x6,g.K);g.h=x6.prototype;g.h.ZK=function(a){this.C=arguments;this.o=!1;this.Ga?this.B=(0,g.H)()+this.Gd:this.Ga=g.eh(this.D,this.Gd)};
g.h.stop=function(){this.Ga&&(g.fh(this.Ga),this.Ga=null);this.B=null;this.o=!1;this.C=[]};
g.h.pause=function(){++this.A};
g.h.resume=function(){this.A&&(--this.A,!this.A&&this.o&&(this.o=!1,this.F.apply(null,this.C)))};
g.h.W=function(){this.stop();x6.ga.W.call(this)};
g.h.aL=function(){this.B?(this.Ga=g.eh(this.D,this.B-(0,g.H)()),this.B=null):(this.Ga=null,this.A?this.o=!0:(this.o=!1,this.F.apply(null,this.C)))};y6.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
y6.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=z6.prototype;g.h.Mi=null;g.h.Hf=!1;g.h.zl=null;g.h.By=null;g.h.Yk=null;g.h.ek=null;g.h.Bh=null;g.h.ci=null;g.h.mj=null;g.h.Xc=null;g.h.ko=0;g.h.Jf=null;g.h.os=null;g.h.Ch=null;g.h.Jm=-1;g.h.KF=!0;g.h.si=!1;g.h.Gu=0;g.h.sr=null;var nFa={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.eV=function(a){a=a.target;var b=this.sr;b&&3==g.Hy(a)?b.Fm():this.SG(a)};
g.h.SG=function(a){try{if(a==this.Xc)a:{var b=g.Hy(this.Xc),c=this.Xc.A,d=this.Xc.getStatus();if(g.fe&&!g.Oc(10)||g.he&&!g.Nc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Uf&&!g.Ly(this.Xc))break a;this.si||4!=b||7==c||(8==c||0>=d?this.o.Bf(3):this.o.Bf(2));J6(this);var e=this.Xc.getStatus();this.Jm=e;var f=g.Ly(this.Xc);(this.Hf=200==e)?(4==b&&F6(this),this.D?(oFa(this,b,f),g.Uf&&this.Hf&&3==b&&(this.Y.X(this.A,"tick",this.ZU),this.A.start())):E6(this,f),this.Hf&&!this.si&&(4==b?this.o.Tq(this):
(this.Hf=!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Ch=3,D6(13)):(this.Ch=0,D6(14)),F6(this),G6(this))}}catch(k){this.Xc&&g.Ly(this.Xc)}finally{}};
g.h.ZU=function(){var a=g.Hy(this.Xc),b=g.Ly(this.Xc);this.ko<b.length&&(J6(this),oFa(this,a,b),this.Hf&&4!=a&&B6(this))};
g.h.mU=function(a){I6((0,g.A)(this.lU,this,a),0)};
g.h.lU=function(a){this.si||(J6(this),E6(this,a),B6(this))};
g.h.ZE=function(a){I6((0,g.A)(this.kU,this,a),0)};
g.h.kU=function(a){this.si||(F6(this),this.Hf=a,this.o.Tq(this),this.o.Bf(4))};
g.h.cancel=function(){this.si=!0;F6(this)};
g.h.BU=function(){this.zl=null;var a=(0,g.H)();0<=a-this.By?(2!=this.ek&&this.o.Bf(3),F6(this),this.Ch=2,D6(18),G6(this)):rFa(this,this.By-a)};
g.h.getLastError=function(){return this.Ch};g.h=uFa.prototype;g.h.Eu=null;g.h.oe=null;g.h.tr=!1;g.h.OB=null;g.h.xp=null;g.h.Kv=null;g.h.Fu=null;g.h.Xe=null;g.h.Rg=-1;g.h.Im=null;g.h.Pl=null;g.h.connect=function(a){this.Fu=a;a=L6(this.o,null,this.Fu);D6(3);this.OB=(0,g.H)();var b=this.o.H;null!=b?(this.Im=b[0],(this.Pl=b[1])?(this.Xe=1,vFa(this)):(this.Xe=2,N6(this))):(d6(a,"MODE","init"),this.oe=new z6(this,void 0,void 0,void 0),this.oe.Mi=this.Eu,A6(this.oe,a,!1,null,!0),this.Xe=0)};
g.h.aK=function(a){if(a)this.Xe=2,N6(this);else{D6(4);var b=this.o;b.Uf=b.rh.Rg;U6(b,9)}a&&this.Bf(2)};
g.h.Yt=function(a){return this.o.Yt(a)};
g.h.abort=function(){this.oe&&(this.oe.cancel(),this.oe=null);this.Rg=-1};
g.h.NB=function(){return!1};
g.h.SE=function(a,b){this.Rg=a.Jm;if(0==this.Xe)if(b){try{var c=this.A.parse(b)}catch(d){c=this.o;c.Uf=this.Rg;U6(c,2);return}this.Im=c[0];this.Pl=c[1]}else c=this.o,c.Uf=this.Rg,U6(c,2);else if(2==this.Xe)if(this.tr)D6(7),this.Kv=(0,g.H)();else if("11111"==b){if(D6(6),this.tr=!0,this.xp=(0,g.H)(),c=this.xp-this.OB,!g.fe||g.Oc(10)||500>c)this.Rg=200,this.oe.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.xp=this.Kv=(0,g.H)(),this.tr=!1};
g.h.Tq=function(){this.Rg=this.oe.Jm;if(this.oe.Hf)0==this.Xe?this.Pl?(this.Xe=1,vFa(this)):(this.Xe=2,N6(this)):2==this.Xe&&((!g.fe||g.Oc(10)?!this.tr:200>this.Kv-this.xp)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Xe?D6(9):2==this.Xe&&D6(10);var a=this.o;this.oe.getLastError();a.Uf=this.Rg;U6(a,2)}};
g.h.Yn=function(){return this.o.Yn()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Bf=function(a){this.o.Bf(a)};g.h=O6.prototype;g.h.jm=null;g.h.ie=null;g.h.Bc=null;g.h.Du=null;g.h.zp=null;g.h.iA=null;g.h.Mp=null;g.h.An=0;g.h.YP=0;g.h.Fd=null;g.h.vh=null;g.h.Dg=null;g.h.Ai=null;g.h.rh=null;g.h.ks=null;g.h.yk=-1;g.h.DC=-1;g.h.Uf=-1;g.h.Vj=0;g.h.Lj=0;g.h.xi=8;var V6=new g.tg;g.B(xFa,g.Sf);g.B(yFa,g.Sf);g.B(zFa,g.Sf);g.h=O6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.Du=b;this.jm=c||{};d&&g.Ba(e)&&(this.jm.OSID=d,this.jm.OAID=e);this.F?(I6((0,g.A)(this.zA,this,a),100),DFa(this)):this.zA(a)};
g.h.zA=function(a){this.rh=new uFa(this);this.rh.Eu=null;this.rh.A=this.D;this.rh.connect(a)};
g.h.NB=function(){return 0==this.o};
g.h.YE=function(a){this.vh=null;GFa(this,a)};
g.h.XE=function(){this.Dg=null;this.Bc=new z6(this,this.B,"rpc",this.G);this.Bc.Mi=null;this.Bc.Gu=0;var a=this.iA.clone();g.Zn(a,"RID","rpc");g.Zn(a,"SID",this.B);g.Zn(a,"CI",this.ks?"0":"1");g.Zn(a,"AID",this.yk);P6(this,a);if(!g.fe||g.Oc(10))g.Zn(a,"TYPE","xmlhttp"),A6(this.Bc,a,!0,this.Mp,!1);else{g.Zn(a,"TYPE","html");var b=this.Bc,c=!!this.Mp;b.ek=3;b.Bh=c6(a.clone());qFa(b,c)}};
g.h.SE=function(a,b){if(0!=this.o&&(this.Bc==a||this.ie==a))if(this.Uf=a.Jm,this.ie==a&&3==this.o)if(7<this.xi){try{var c=this.D.parse(b)}catch(f){c=null}if(g.Ia(c)&&3==c.length)if(0==c[0])a:{if(!this.Dg){if(this.Bc)if(this.Bc.Yk+3E3<this.ie.Yk)R6(this),this.Bc.cancel(),this.Bc=null;else break a;T6(this);D6(19)}}else this.DC=c[1],0<this.DC-this.yk&&37500>c[2]&&this.ks&&0==this.Lj&&!this.Ai&&(this.Ai=I6((0,g.A)(this.CQ,this),6E3));else U6(this,11)}else b!=bHa.fZ.o&&U6(this,11);else if(this.Bc==a&&
R6(this),!g.E(b)){c=this.D.parse(b);g.Ia(c);for(var d=0;d<c.length;d++){var e=c[d];this.yk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.B=e[1],this.Mp=e[2],e=e[3],null!=e?this.xi=e:this.xi=6,this.o=3,this.Fd&&this.Fd.uA(),this.iA=L6(this,this.Yn()?this.Mp:null,this.Du),HFa(this)):"stop"==e[0]&&U6(this,7):3==this.o&&("stop"==e[0]?U6(this,7):"noop"!=e[0]&&this.Fd&&this.Fd.tA(e),this.Lj=0)}}};
g.h.CQ=function(){null!=this.Ai&&(this.Ai=null,this.Bc.cancel(),this.Bc=null,T6(this),D6(20))};
g.h.Tq=function(a){if(this.Bc==a){R6(this);this.Bc=null;var b=2}else if(this.ie==a)this.ie=null,b=1;else return;this.Uf=a.Jm;if(0!=this.o)if(a.Hf)1==b?(b=(0,g.H)()-a.Yk,V6.dispatchEvent(new yFa(V6,a.mj?a.mj.length:0,b,this.Vj)),Q6(this),this.C.length=0):HFa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Uf)){if(d=1==b)this.ie||this.vh||1==this.o||2<=this.Vj?d=!1:(this.vh=I6((0,g.A)(this.YE,this,a),IFa(this,this.Vj)),this.Vj++,d=!0);d=!(d||2==b&&T6(this))}if(d)switch(c){case 1:U6(this,
5);break;case 4:U6(this,10);break;case 3:U6(this,6);break;case 7:U6(this,12);break;default:U6(this,2)}}};
g.h.wK=function(a){if(!g.ab(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.VV=function(a){a?D6(2):(D6(1),JFa(this,8))};
g.h.Yt=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.By;a.H=!1;return a};
g.h.isActive=function(){return!!this.Fd&&this.Fd.isActive(this)};
g.h.Bf=function(a){V6.dispatchEvent(new zFa(V6,a))};
g.h.Yn=function(){return!(!g.fe||g.Oc(10))};
g.h=KFa.prototype;g.h.uA=function(){};
g.h.tA=function(){};
g.h.sA=function(){};
g.h.Lt=function(){};
g.h.tB=function(){return{}};
g.h.isActive=function(){return!0};g.B(W6,g.K);g.h=W6.prototype;g.h.cU=function(){this.Gd=Math.min(3E5,2*this.Gd);this.B();this.A&&this.start()};
g.h.start=function(){var a=this.Gd+15E3*Math.random();g.Av(this.o,a);this.A=(0,g.H)()+a};
g.h.stop=function(){this.o.stop();this.A=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Gd=5E3};g.B(X6,KFa);g.h=X6.prototype;g.h.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.h.Dk=function(a){return this.B.Ni(a)};
g.h.V=function(a,b){return this.B.V.apply(this.B,arguments)};
g.h.dispose=function(){this.Bb||(this.Bb=!0,g.Qf(this.B),NFa(this),g.Qf(this.A),this.A=null)};
g.h.la=function(){return this.Bb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.J="";this.A.stop();this.D=a||null;this.C=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new O6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.L),e=this.o;e&&(e.Fd=null);d.Fd=this;this.o=d;e?this.o.connect(a,b,this.F,e.B,e.yk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.mc(c,b);this.A.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):Y6(this)&&EFa(this.o,c)};
g.h.uA=function(){this.A.reset();this.D=null;this.C=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)EFa(this.o,a[b])}this.V("handlerOpened")};
g.h.sA=function(a){var b=2==a&&401==this.o.Uf;4==a||b||this.A.start();this.V("handlerError",a)};
g.h.Lt=function(a){if(!this.A.isActive())this.V("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.tB=function(){var a={v:2};this.J&&(a.gsessionid=this.J);0!=this.C&&(a.ui=""+this.C);0!=this.H&&(a.ui=""+this.H);this.D&&g.mc(a,this.D);return a};
g.h.tA=function(a){"S"==a[0]?this.J=a[1]:"gracefulReconnect"==a[0]?(this.A.start(),CFa(this.o)):this.V("handlerMessage",new LFa(a[0],a[1]))};
g.h.zW=function(){this.A.isActive();var a=this.o,b=0;a.Bc&&b++;a.ie&&b++;0!=b||this.connect(this.D,this.C)};Z6.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Z6.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
Z6.prototype.D=function(a){a(Error("request timed out"))};var VFa=(0,g.H)(),b7=null,e7=Array(50),d7=-1,f7=!1;g.B(g7,g.uH);g7.prototype.ze=function(){return this.o};
g7.prototype.contains=function(a){return!!l6(this.o,a)};
g7.prototype.get=function(a){return a?m6(this.o,a):null};
g7.prototype.info=function(a){c7(this.G,a)};g.B(h7,g.uH);var cHa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=h7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ga)&&this.UG()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ga)||(g.qF(this.Ga),this.Ga=NaN)};
g.h.W=function(){this.stop();h7.ga.W.call(this)};
g.h.UG=function(){this.Ga=NaN;this.o=g.cG($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:this.D},timeout:5E3,onSuccess:(0,g.A)(this.BW,this),onError:(0,g.A)(this.AW,this),Jd:(0,g.A)(this.DW,this)})};
g.h.BW=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.C;this.V("pairingComplete",new g6(c))};
g.h.AW=function(a){this.o=null;a.status&&404==a.status?this.A>=cHa.length?this.V("pairingFailed",Error("DIAL polling timed out")):(a=cHa[this.A],this.Ga=g.oF((0,g.A)(this.UG,this),a),this.A++):this.V("pairingFailed",Error("Server error "+a.status))};
g.h.DW=function(){this.o=null;this.V("pairingFailed",Error("Server not responding"))};g.B(j7,g7);g.h=j7.prototype;g.h.start=function(){i7(this)&&this.V("screenChange");!g.JI("yt-remote-lounge-token-expiration")&&ZFa(this);g.qF(this.A);this.A=g.oF((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){i7(this);WFa(this,a);k7(this,!1);this.V("screenChange");b(a);a.token||ZFa(this)};
g.h.remove=function(a,b){var c=i7(this);YFa(this,a)&&(k7(this,!1),c=!0);b(a);c&&this.V("screenChange")};
g.h.ds=function(a,b,c,d){var e=i7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,k7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.V("screenChange")};
g.h.W=function(){g.qF(this.A);j7.ga.W.call(this)};
g.h.oL=function(a){i7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}k7(this,!b);b&&c7(this.G,"Missed "+b+" lounge tokens.")};
g.h.nL=function(a){c7(this.G,"Requesting lounge tokens failed: "+a)};g.B(m7,g.uH);g.h=m7.prototype;g.h.start=function(){var a=parseInt(g.JI("yt-remote-fast-check-period")||"0",10);(this.C=(0,g.H)()-144E5<a?0:a)?o7(this):(this.C=(0,g.H)()+3E5,g.II("yt-remote-fast-check-period",this.C),this.ox())};
g.h.isEmpty=function(){return g.ec(this.o)};
g.h.update=function(){l7("Updating availability on schedule.");var a=this.F(),b=g.Qb(this.o,function(c,d){return c&&!!m6(a,d)},this);
n7(this,b)};
g.h.W=function(){g.qF(this.B);this.B=NaN;this.A&&(this.A.abort(),this.A=null);m7.ga.W.call(this)};
g.h.ox=function(){g.qF(this.B);this.B=NaN;this.A&&this.A.abort();var a=bGa(this);if(g.Ub(a)){var b=$6(this.D,"/pairing/get_screen_availability");this.A=a7(this.D,b,{lounge_token:g.Xb(a).join(",")},(0,g.A)(this.ET,this,a),(0,g.A)(this.DT,this))}else n7(this,{}),o7(this)};
g.h.ET=function(a,b){this.A=null;var c=g.Xb(bGa(this));if(g.vb(c,g.Xb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;n7(this,d);o7(this)}else this.sc("Changing Screen set during request."),this.ox()};
g.h.DT=function(a){this.sc("Screen availability failed: "+a);this.A=null;o7(this)};
g.h.sc=function(a){c7("OnlineScreenService",a)};g.B(p7,g7);g.h=p7.prototype;g.h.start=function(){this.B.start();this.A.start();this.o.length&&(this.V("screenChange"),this.A.isEmpty()||this.V("onlineScreenChange"))};
g.h.add=function(a,b,c){this.B.add(a,b,c)};
g.h.remove=function(a,b,c){this.B.remove(a,b,c);this.A.update()};
g.h.ds=function(a,b,c,d){this.B.contains(a)?this.B.ds(a,b,c,d):(a="Updating name of unknown screen: "+a.name,c7(this.G,a),d(Error(a)))};
g.h.ze=function(a){return a?this.o:g.jb(this.o,(0,g.te)(this.C,function(b){return!this.contains(b)},this))};
g.h.VG=function(){return(0,g.te)(this.ze(!0),function(a){return!!this.A.o[a.id]},this)};
g.h.WG=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new h7(this.F,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(k){g.Qf(f);d(q7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Qf(f);e(k)});
f.start();return(0,g.A)(f.stop,f)};
g.h.FW=function(a,b,c,d){g.cG($6(this.F,"/pairing/get_screen"),{method:"POST",Sb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.A)(function(e,f){var k=new g6(f.screen||{});if(!k.name||fGa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);fGa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(q7(this,k))},this),
onError:(0,g.A)(function(e){d(Error("pairing request failed: "+e.status))},this),
Jd:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.W=function(){g.Qf(this.B);g.Qf(this.A);p7.ga.W.call(this)};
g.h.BL=function(){gGa(this);this.V("screenChange");this.A.update()};
p7.prototype.dispose=p7.prototype.dispose;g.B(s7,g.uH);g.h=s7.prototype;g.h.Uq=function(a){this.B=a;this.V("sessionScreen",this.B)};
g.h.Ee=function(a){this.la()||(a&&t7(this,""+a),this.B=null,this.V("sessionScreen",null))};
g.h.info=function(a){c7(this.R,a)};
g.h.YG=function(){return null};
g.h.Dx=function(a){var b=this.A;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){t7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.W=function(){this.Dx("");s7.ga.W.call(this)};g.B(u7,s7);g.h=u7.prototype;g.h.Cx=function(a){if(this.o){if(this.o==a)return;t7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.F);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D)}this.o=a;this.o.addUpdateListener(this.F);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.D);iGa(this)};
g.h.Ak=function(a){this.info("launchWithParams no-op for Cast: "+g.jh(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.A)(function(){this.Ee()},this),(0,g.A)(function(){this.Ee(Error("Failed to stop receiver app."))},this)):this.Ee(Error("Stopping cast device witout session."))};
g.h.Dx=g.z;g.h.W=function(){this.info("disposeInternal");g.qF(this.C);this.C=0;this.o&&(this.o.removeUpdateListener(this.F),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.D));this.o=null;u7.ga.W.call(this)};
g.h.NU=function(a,b){if(!this.la())if(b){var c=g.vy(b);if(g.La(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.jh(c));switch(d){case "mdxSessionStatus":hGa(this,c.screenId);break;default:t7(this,"Unknown youtube message: "+d)}}else t7(this,"Unable to parse message.")}else t7(this,"No data in message.")};
g.h.EB=function(a,b,c,d){eGa(this.J,this.A.label,a,this.A.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(t7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.oF((0,g.A)(this.EB,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.YG=function(){return this.o};
g.h.GW=function(a){this.la()||a||(t7(this,"Cast session died."),this.Ee())};g.B(v7,s7);g.h=v7.prototype;g.h.Cx=function(a){this.C=a;this.C.addUpdateListener(this.L)};
g.h.Ak=function(a){this.D=a;this.G()};
g.h.stop=function(){this.o();this.o=g.z;g.qF(this.F);this.C?this.C.stop((0,g.A)(this.Ee,this,null),(0,g.A)(this.Ee,this,"Failed to stop DIAL device.")):this.Ee()};
g.h.W=function(){this.o();this.o=g.z;g.qF(this.F);this.C&&this.C.removeUpdateListener(this.L);this.C=null;v7.ga.W.call(this)};
g.h.JW=function(a){this.la()||a||(t7(this,"DIAL session died."),this.o(),this.o=g.z,this.Ee())};
g.h.hv=function(a){this.K=k6();if(this.D){var b=new chrome.cast.DialLaunchResponse(!0,kGa(this));a(b);jGa(this)}else this.G=(0,g.A)(function(){g.qF(this.F);this.G=g.z;this.F=NaN;var c=new chrome.cast.DialLaunchResponse(!0,kGa(this));a(c);jGa(this)},this),this.F=g.oF((0,g.A)(function(){this.G()},this),100)};
g.h.OM=function(a,b,c){eGa(this.J,this.H.receiver.label,a,this.A.friendlyName,(0,g.A)(function(d){d&&d.token?(this.Uq(d),b(new chrome.cast.DialLaunchResponse(!1))):this.hv(b,c)},this),(0,g.A)(function(d){t7(this,"Failed to get DIAL screen: "+d);
this.hv(b,c)},this))};g.B(w7,s7);w7.prototype.stop=function(){this.Ee()};
w7.prototype.Cx=g.z;w7.prototype.Ak=function(){g.qF(this.o);this.o=NaN;var a=m6(this.J.ze(),this.A.label);a?this.Uq(a):this.Ee(Error("No such screen"))};
w7.prototype.W=function(){g.qF(this.o);this.o=NaN;w7.ga.W.call(this)};g.B(x7,g.uH);g.h=x7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.A)(this.UE,this),(0,g.A)(this.mT,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.kR,this);chrome.cast.initialize(c,(0,g.A)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.C),SFa(),this.A.subscribe("onlineScreenChange",(0,g.A)(this.XG,this)),this.B=mGa(this),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(f){this.sc("Failed to set initial custom receivers: "+g.jh(f))},this)),this.V("yt-remote-cast2-availability-change",z7(this)),b(!0))},this),(0,g.A)(function(f){this.sc("Failed to initialize API: "+g.jh(f));
b(!1)},this))};
g.h.CV=function(a,b){y7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.B;if(!a||c&&c.id!=a)y7("Unsetting old screen status: "+this.o.A.friendlyName),A7(this,null)}if(a&&b){if(!this.o){c=m6(this.A.ze(),a);if(!c){y7("setConnectedScreenStatus: Unknown screen.");return}var d=lGa(this,c);d||(y7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(d),chrome.cast.setCustomReceivers(this.B,
g.z,(0,g.A)(function(e){this.sc("Failed to set initial custom receivers: "+g.jh(e))},this)));
y7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);A7(this,new w7(this.A,d),!0)}this.o.Dx(b)}else y7("setConnectedScreenStatus: no screen.")};
g.h.EV=function(a){this.la()?this.sc("Setting connection data on disposed cast v2"):this.o?this.o.Ak(a):this.sc("Setting connection data without a session")};
g.h.IW=function(){this.la()?this.sc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),A7(this,null)):y7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.A)(this.UE,this),(0,g.A)(this.IT,this))};
g.h.W=function(){this.A.unsubscribe("onlineScreenChange",(0,g.A)(this.XG,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.C);g.fb(g.y("yt.mdx.remote.debug.handlers_")||[],PFa);g.Qf(this.o);x7.ga.W.call(this)};
g.h.sc=function(a){c7("Controller",a)};
g.h.VE=function(a,b){this.o==a&&(b||A7(this,null),this.V("yt-remote-cast2-session-change",b))};
g.h.iT=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),y7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.A.label!=a.label)y7("onReceiverAction_: Stopping active receiver: "+this.o.A.friendlyName),this.o.stop();else{y7("onReceiverAction_: Casting to active receiver.");this.o.B&&this.V("yt-remote-cast2-session-change",this.o.B);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:A7(this,
new w7(this.A,a));break;case chrome.cast.ReceiverType.DIAL:A7(this,new v7(this.A,a,this.F));break;case chrome.cast.ReceiverType.CAST:A7(this,new u7(this.A,a));break;default:this.sc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.A.label==a.label?this.o.stop():this.sc("Stopping receiver w/o session: "+a.friendlyName)}else this.sc("onReceiverAction_ called without receiver.")};
g.h.kR=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.sc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.A:null;if(!c||c.label!=b.label)return this.sc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.B)return y7("Reselecting dial screen."),
this.V("yt-remote-cast2-session-change",this.o.B),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.sc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);A7(this,new v7(this.A,b,this.F))}b=this.o;b.H=a;return b.H.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.A)(b.OM,b,(b.H.extraData||{}).screenId||null)):new Promise((0,g.A)(b.hv,b))};
g.h.UE=function(a){if(!this.la()){y7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)y7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),A7(this,new u7(this.A,b),!0);else{this.sc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.A,d=m6(this.A.ze(),c.label);d&&h6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(y7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Qf(this.o),this.o=new u7(this.A,b),this.o.subscribe("sessionScreen",(0,g.A)(this.VE,this,this.o)),this.o.Ak(null));this.o.Cx(a)}}};
g.h.HW=function(){return this.o?this.o.YG():null};
g.h.IT=function(a){this.la()||(this.sc("Failed to estabilish a session: "+g.jh(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&A7(this,null))};
g.h.mT=function(a){y7("Receiver availability updated: "+a);if(!this.la()){var b=z7(this);this.D=a==chrome.cast.ReceiverAvailability.AVAILABLE;z7(this)!=b&&this.V("yt-remote-cast2-availability-change",z7(this))}};
g.h.XG=function(){this.la()||(this.B=mGa(this),y7("Updating custom receivers: "+g.jh(this.B)),chrome.cast.setCustomReceivers(this.B,g.z,(0,g.A)(function(){this.sc("Failed to set custom receivers.")},this)),this.V("yt-remote-cast2-availability-change",z7(this)))};
x7.prototype.setLaunchParams=x7.prototype.EV;x7.prototype.setConnectedScreenStatus=x7.prototype.CV;x7.prototype.stopSession=x7.prototype.IW;x7.prototype.getCastSession=x7.prototype.HW;x7.prototype.requestSession=x7.prototype.requestSession;x7.prototype.init=x7.prototype.init;x7.prototype.dispose=x7.prototype.dispose;var G7=[];g.h=L7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";M7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.Yf=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.A=a.seekableEnd,this.H=a.duration,this.J=a.loadedTime,this.B=a.liveIngestionTime,this.D=!isNaN(this.B))};
g.h.tb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.D?this.H+N7(this):this.H};
g.h.clone=function(){return new L7(R7(this))};g.B(T7,g.uH);g.h=T7.prototype;g.h.play=function(){1==this.o?(this.A?this.A.play(null,g.z,Z7(this,"play")):Y7(this,"play"),X7(this,1,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.play)};
g.h.pause=function(){1==this.o?(this.A?this.A.pause(null,g.z,Z7(this,"pause")):Y7(this,"pause"),X7(this,2,P7(U7(this))),this.V("remotePlayerChange")):V7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.A){var b=U7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.tb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.A.seek(c,g.z,Z7(this,"seekTo",{newTime:a}))}else Y7(this,"seekTo",{newTime:a});X7(this,3,a);this.V("remotePlayerChange")}else V7(this,g.Oa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.A?this.A.stop(null,g.z,Z7(this,"stopVideo")):Y7(this,"stopVideo");var a=U7(this);a.index=-1;a.videoId="";M7(a);W7(this,a);this.V("remotePlayerChange")}else V7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=U7(this);if(this.B){if(c.volume!=a){var d=Math.round(a)/100;this.B.setReceiverVolumeLevel(d,(0,g.A)(function(){c7("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.sc("failed to set receiver volume.")},this))}c.muted!=b&&this.B.setReceiverMuted(b,(0,g.A)(function(){c7("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.sc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Y7(this,"setVolume",e)}c.muted=b;c.volume=a;W7(this,c)}else V7(this,g.Oa(this.setVolume,a,b))};
g.h.YF=function(a,b){if(1==this.o){var c=U7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.jh(b.style),g.mc(d,c.o));Y7(this,"setSubtitlesTrack",d);W7(this,c)}else V7(this,g.Oa(this.YF,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();Y7(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=U7(this);d.audioTrackId=c;W7(this,d)}else V7(this,g.Oa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=U7(this);c=c||0;var m={videoId:a,currentIndex:c};Q7(l,a,c);g.Ba(b)&&(O7(l,b),m.currentTime=b);g.Ba(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.jh(k));Y7(this,"setPlaylist",m);d||W7(this,l)};
g.h.dr=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"previous")}else V7(this,g.Oa(this.dr,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=U7(this);Q7(c,a,b);W7(this,c)}Y7(this,"next")}else V7(this,g.Oa(this.nextVideo,a,b))};
g.h.TA=function(){1==this.o?Y7(this,"dismissAutoplay"):V7(this,this.TA)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.V("proxyStateChange",a,this.o)}T7.ga.dispose.call(this)};
g.h.W=function(){zGa(this);this.C=null;this.D.clear();S7(this,null);T7.ga.W.call(this)};
g.h.Jy=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.V("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)g.ND(this.D).apply(this);else 3==a&&this.dispose()}};
g.h.eT=function(a,b){this.V(a,b)};
g.h.JQ=function(a){if(!a)this.En(null),S7(this,null);else if(this.B.receiver.volume){a=this.B.receiver.volume;var b=U7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)c7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,W7(this,b)}};
g.h.En=function(a){c7("CP","Cast media: "+!!a);this.A&&this.A.removeUpdateListener(this.H);if(this.A=a)this.A.addUpdateListener(this.H),AGa(this),this.V("remotePlayerChange")};
g.h.IQ=function(a){a?(AGa(this),this.V("remotePlayerChange")):this.En(null)};
g.h.Xx=function(){Y7(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.VQ=function(){var a=wGa();a&&S7(this,a)};
g.h.sc=function(a){c7("CP",a)};g.B($7,g.uH);g.h=$7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ba(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ba(k)&&(l.currentIndex=k);c&&(this.qb.listId=c);this.qb.videoId=d;this.qb.index=k||0;this.qb.state=3;O7(this.qb,m);this.C="UNSUPPORTED";a8("Connecting with setPlaylist and params: "+g.jh(l));this.o.connect({method:"setPlaylist",
params:g.jh(l)},a,ZEa())}else a8("Connecting without params"),this.o.connect({},a,ZEa());CGa(this)};
g.h.dispose=function(){this.la()||(this.V("beforeDispose"),b8(this,3));$7.ga.dispose.call(this)};
g.h.W=function(){c8(this);e8(this);d8(this);g.qF(this.J);this.J=NaN;g.qF(this.K);this.K=NaN;this.B=null;g.eH(this.T);this.T.length=0;this.o.dispose();$7.ga.W.call(this);this.C=this.G=this.A=this.qb=this.o=null};
g.h.eL=function(){this.F(2)};
g.h.NQ=function(){a8("Channel opened");this.N&&(this.N=!1,d8(this),this.R=g.oF((0,g.A)(function(){a8("Timing out waiting for a screen.");this.F(1)},this),15E3));
cFa(MFa(this.o),this.aa)};
g.h.KQ=function(){a8("Channel closed");isNaN(this.D)?r6(!0):r6();this.dispose()};
g.h.LQ=function(a){r6();isNaN(this.H())?(a8("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,a8("Channel error: "+a+" with reconnection in "+this.H()+" ms"),b8(this,2))};
g.h.MQ=function(a){a.params?a8("Received: action="+a.action+", params="+g.jh(a.params)):a8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.vy(a.params.devices);this.A=(0,g.J)(a,function(c){return new f6(c)});
a=!!g.Wa(this.A,function(c){return"LOUNGE_SCREEN"==c.type});
FGa(this,a);break;case "loungeScreenDisconnected":g.gb(this.A,function(c){return"LOUNGE_SCREEN"==c.type});
FGa(this,!1);break;case "remoteConnected":var b=new f6(g.vy(a.params.device));g.Wa(this.A,function(c){return b?c.id==b.id:!1})||g.db(this.A,b);
break;case "remoteDisconnected":b=new f6(g.vy(a.params.device));g.gb(this.A,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":HGa(this,a);break;case "nowPlaying":JGa(this,a);break;case "onStateChange":IGa(this,a);break;case "onAdStateChange":KGa(this,a);break;case "onVolumeChanged":LGa(this,a);break;case "onSubtitlesTrackChanged":GGa(this,a);break;case "nowAutoplaying":MGa(this,a);break;case "autoplayDismissed":this.V("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.V("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.V("autoplayModeChange",this.C);"DISABLED"==this.C&&this.V("autoplayDismissed");break;case "onHasPreviousNextChanged":NGa(this,a);break;case "requestAssistedSignIn":this.V("assistedSignInRequested",a.params.authCode);break;default:a8("Unrecognized action: "+a.action)}};
g.h.mV=function(){if(this.B){var a=this.B;this.B=null;this.qb.videoId!=a&&f8(this,"getNowPlaying")}};
$7.prototype.subscribe=$7.prototype.subscribe;$7.prototype.unsubscribeByKey=$7.prototype.Dk;$7.prototype.ha=function(){var a=3;this.la()||(a=0,isNaN(this.H())?Y6(this.o)&&isNaN(this.D)&&(a=1):a=2);return a};
$7.prototype.getProxyState=$7.prototype.ha;$7.prototype.F=function(a){a8("Disconnecting with "+a);c8(this);this.V("beforeDisconnect",a);1==a&&r6();NFa(this.o,a);this.dispose()};
$7.prototype.disconnect=$7.prototype.F;$7.prototype.ea=function(){var a=this.qb;this.B&&(a=this.qb.clone(),Q7(a,this.B,a.index));return R7(a)};
$7.prototype.getPlayerContextData=$7.prototype.ea;
$7.prototype.ma=function(a){var b=new L7(a);b.videoId&&b.videoId!=this.qb.videoId&&(this.B=b.videoId,g.qF(this.J),this.J=g.oF((0,g.A)(this.mV,this),5E3));var c=[];this.qb.listId==b.listId&&this.qb.videoId==b.videoId&&this.qb.index==b.index||c.push("remoteQueueChange");this.qb.playerState==b.playerState&&this.qb.volume==b.volume&&this.qb.muted==b.muted&&P7(this.qb)==P7(b)&&g.jh(this.qb.o)==g.jh(b.o)||c.push("remotePlayerChange");this.qb.reset(a);(0,g.C)(c,function(d){this.V(d)},this)};
$7.prototype.setPlayerContextData=$7.prototype.ma;$7.prototype.Z=function(){var a=this.o.F.id,b=g.Wa(this.A,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
$7.prototype.getOtherConnectedRemoteId=$7.prototype.Z;$7.prototype.H=function(){var a=this.o;return a.A.isActive()?a.A.A-(0,g.H)():NaN};
$7.prototype.getReconnectTimeout=$7.prototype.H;$7.prototype.fa=function(){return this.C||"UNSUPPORTED"};
$7.prototype.getAutoplayMode=$7.prototype.fa;$7.prototype.da=function(){return this.G||""};
$7.prototype.getAutoplayVideoId=$7.prototype.da;$7.prototype.za=function(){if(!isNaN(this.H())){var a=this.o.A;g.Bv(a.o);a.start()}};
$7.prototype.reconnect=$7.prototype.za;$7.prototype.ka=function(a,b){f8(this,a,b);EGa(this)};
$7.prototype.sendMessage=$7.prototype.ka;g.B(g8,g7);g.h=g8.prototype;g.h.ze=function(a){return this.kd.$_gs(a)};
g.h.contains=function(a){return!!this.kd.$_c(a)};
g.h.get=function(a){return this.kd.$_g(a)};
g.h.start=function(){this.kd.$_st()};
g.h.add=function(a,b,c){this.kd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.kd.$_r(a,b,c)};
g.h.ds=function(a,b,c,d){this.kd.$_un(a,b,c,d)};
g.h.W=function(){for(var a=0,b=this.A.length;a<b;++a)this.kd.$_ubk(this.A[a]);this.A.length=0;this.kd=null;g8.ga.W.call(this)};
g.h.EW=function(){this.V("screenChange")};
g.h.DS=function(){this.V("onlineScreenChange")};
p7.prototype.$_st=p7.prototype.start;p7.prototype.$_gspc=p7.prototype.FW;p7.prototype.$_gsppc=p7.prototype.WG;p7.prototype.$_c=p7.prototype.contains;p7.prototype.$_g=p7.prototype.get;p7.prototype.$_a=p7.prototype.add;p7.prototype.$_un=p7.prototype.ds;p7.prototype.$_r=p7.prototype.remove;p7.prototype.$_gs=p7.prototype.ze;p7.prototype.$_gos=p7.prototype.VG;p7.prototype.$_s=p7.prototype.subscribe;p7.prototype.$_ubk=p7.prototype.Dk;var h8=null,i8=null,x8=null,m8=[];g.t(y8,g.K);g.h=y8.prototype;
g.h.W=function(){g.K.prototype.W.call(this);this.C.stop();this.F.stop();this.L.stop();this.N();this.o.unsubscribe("proxyStateChange",this.RE,this);this.o.unsubscribe("remotePlayerChange",this.Hn,this);this.o.unsubscribe("remoteQueueChange",this.Vq,this);this.o.unsubscribe("autoplayUpNext",this.oE,this);this.o.unsubscribe("previousNextChange",this.OE,this);this.o.unsubscribe("nowAutoplaying",this.GE,this);this.o.unsubscribe("autoplayDismissed",this.nE,this);this.o=this.D=null};
g.h.rD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(B8(this)){if(!U7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":U7(this.o).tb()?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.K.Fm(c[0],c[1]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.A.getCurrentTime();D8(this,0==c?void 0:c);break;case "control_seek":D8(this,c[0]);break;case "control_subtitles_set_track":C8(this,c[0]);break;case "control_set_audio_track":c=c[0],B8(this)&&this.o.setAudioTrack(this.A.getVideoData(1).videoId,c)}};
g.h.HQ=function(a){this.L.ZK(a)};
g.h.fW=function(a){this.rD("control_subtitles_set_track",g.ec(a)?null:a)};
g.h.nG=function(){var a=this.A.getOption("captions","track");g.ec(a)||C8(this,a)};
g.h.CE=function(a){if(B8(this)){this.o.unsubscribe("remotePlayerChange",this.Hn,this);var b=Math.round(a.volume);a=!!a.muted;var c=U7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.R.start();this.o.subscribe("remotePlayerChange",this.Hn,this)}};
g.h.WR=function(){g.ec(this.G)||ZGa(this,this.G);this.H=!1};
g.h.RE=function(a,b){this.F.stop();2==b&&this.lG()};
g.h.Hn=function(){if(B8(this)){this.C.stop();var a=U7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.D.dl(1);break;case 1082:case 1083:this.D.dl(0);break;default:this.D.dl(-1)}switch(a.playerState){case 1081:case 1:A8(this,new g.GQ(8));this.kG();break;case 1085:case 3:A8(this,new g.GQ(9));break;case 1083:case 0:A8(this,new g.GQ(2));this.K.stop();z8(this,this.A.getVideoData().lengthSeconds);break;case 1084:A8(this,new g.GQ(4));break;case 2:A8(this,new g.GQ(4));z8(this,P7(a));
break;case -1:A8(this,new g.GQ(64));break;case -1E3:A8(this,new g.GQ(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=U7(this.o).o;var b=this.G;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.G=a,ZGa(this,a));a=U7(this.o);-1==a.volume||Math.round(this.A.getVolume())==a.volume&&this.A.isMuted()==a.muted||this.R.isActive()||this.JG()}else YGa(this)};
g.h.OE=function(){this.A.V("mdxpreviousnextchange")};
g.h.Vq=function(){B8(this)||YGa(this)};
g.h.ZJ=function(){this.o.TA()};
g.h.oE=function(a){a&&(a=g.cG("/watch_queue_ajax",{method:"GET",ed:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.A)(this.oU,this)}))&&(this.N=(0,g.A)(a.abort,a))};
g.h.oU=function(a,b){var c=new g.zP(g.Y(this.A),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.A.V("mdxautoplayupnext",c)};
g.h.GE=function(a){isNaN(a)||this.A.V("mdxnowautoplaying",a)};
g.h.nE=function(){this.A.V("mdxautoplaycanceled")};
g.h.DO=function(a,b){-1==U7(this.o).playerState?D8(this,a):b&&this.o.seekTo(a)};
g.h.JG=function(){if(B8(this)){var a=U7(this.o);this.B.La(this.T);a.muted?this.A.mute():this.A.unMute();this.A.setVolume(a.volume);this.T=this.B.P(this.A,"onVolumeChange",this.CE)}};
g.h.kG=function(){this.C.stop();if(!this.o.la()){var a=U7(this.o);a.tb()&&A8(this,new g.GQ(8));z8(this,P7(a));this.C.start()}};
g.h.lG=function(){this.F.stop();this.C.stop();var a=this.o.C.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.F.start()};g.t(E8,g.W);E8.prototype.D=function(a){aHa(this,a.state)};g.t(F8,g.ZW);F8.prototype.L=function(){var a=this.B.getOption("remote","receivers");a&&1<a.length&&!this.B.getOption("remote","quickCast")?(this.J=g.xb(a,this.F,this),g.$W(this,(0,g.J)(a,this.F)),a=this.B.getOption("remote","currentReceiver"),this.Af(this.F(a)),this.enable(!0)):this.enable(!1)};
F8.prototype.F=function(a){return a.key};
F8.prototype.zf=function(a){return"cast-selector-receiver"==a?"Cast...":this.J[a].name};
F8.prototype.md=function(a){g.ZW.prototype.md.call(this,a);this.B.setOption("remote","currentReceiver",this.J[a]);this.C.Jb()};g.t(G8,g.lV);g.h=G8.prototype;g.h.create=function(){SGa(g.cO(g.Y(this.player)));this.D.push(g.vF("yt-remote-before-disconnect",this.DQ,this));this.D.push(g.vF("yt-remote-connection-change",this.nT,this));this.D.push(g.vF("yt-remote-receiver-availability-change",this.PE,this));this.D.push(g.vF("yt-remote-auto-connect",this.lT,this));this.D.push(g.vF("yt-remote-receiver-resumed",this.kT,this));this.PE()};
g.h.load=function(){this.player.cancelPlayback();g.lV.prototype.load.call(this);this.C=new y8(this,this.player,this.o);var a=(a=XGa())?a.currentTime:0;var b=w8()?new T7(r8(),void 0):null;0==a&&b&&(a=P7(U7(b)));0!=a&&this.Ie(a);$Ga(this,this.pn,this.pn);g.D0(this.player.app,6)};
g.h.unload=function(){this.player.V("mdxautoplaycanceled");this.B=this.A;g.Rf(this.C,this.o);this.o=this.C=null;g.lV.prototype.unload.call(this);g.D0(this.player.app,5)};
g.h.W=function(){g.wF(this.D);g.lV.prototype.W.call(this)};
g.h.Xh=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.C.rD.apply(this.C,[a].concat(g.ea(c)))};
g.h.dl=function(a){this.H=a};
g.h.getAdState=function(){return this.H};
g.h.TK=function(){return this.loaded?this.C.suggestion:null};
g.h.Yf=function(){return this.o?U7(this.o).Yf:!1};
g.h.hasNext=function(){return this.o?U7(this.o).hasNext:!1};
g.h.Ie=function(a,b){this.J=a||0;this.player.V("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.J};
g.h.getProgressState=function(){var a=U7(this.o),b=this.player.getVideoData();return{allowSeeking:g.Y(this.player).experiments.o("web_player_mdx_allow_seeking_change_killswitch")?this.player.Mc():!a.isAdPlaying()&&this.player.Mc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.D?a.B+N7(a):a.B,isAtLiveHead:1>=(a.D?a.A+N7(a):a.A)-this.getCurrentTime(),loaded:a.J,seekableEnd:a.D?a.A+N7(a):a.A,seekableStart:0<a.C?a.C+N7(a):
a.C}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.dr=function(){this.o&&this.o.dr()};
g.h.DQ=function(a){1==a&&(this.G=this.o?U7(this.o):null)};
g.h.nT=function(){var a=w8()?new T7(r8(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.G=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Qf(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.G)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,P7(a)));this.player.V("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.PE=function(){this.F=[this.A].concat(UGa());var a=s8()||this.A;H8(this,a);this.player.Ca("onMdxReceiversChange")};
g.h.lT=function(){var a=s8();H8(this,a)};
g.h.kT=function(){this.B=s8()};
g.h.Ic=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?J7():H8(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&J7(),!0):!1}};
g.h.Xx=function(){this.o.Xx()};
g.h.wc=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.VZ.remote=G8;})(_yt_player);
